var str, ranMood, ranJob, ranJSONItem, grabJSObj, grabItem, output, 
    moodsJSON   = [
      "an angry",
      "an ambitious",
      "an energized",
      "an energetic",
      "an exhilarated",
      "an exhausted",
      "an exhilarated",
      "an exhausted",
      "an idyllic",
      "an intelligent",
      "an ominous",
      "a blind",
      "a calm",
      "a cheerful",
      "a creepy",
      "a clumsy",
      "a depressed",
      "a disabled",
      "a fearful",
      "a geeky",
      "a gloomy",
      "a greedy",
      "a hopeful",
      "a humorous",
      "a lighthearted",
      "a lonely", 
      "a mad",
      "a melancholy",
      "a mysterious",
      "a nerdy",
      "a one-legged",
      "a reflective",
      "a romantic",
      "a sad",
      "a sleepy",
      "a smart",
      "a strict",
      "a tense",
      "a thrilled",
      "a tired",
      "a whimsical",
      "a battle damaged hero"
    ],
    jobsJSON    = [
      "secret vigilante",
      
      // jobs list acquired from https://joboutlook.gov.au/A-Z
      "Aboriginal and Torres Strait Islander Education Worker",
      "Accommodation and Hospitality Manager",
      "Accountant",
      "Accounting Clerk",
      "Actor",
      "Actor, Dancer and Other Entertainer",
      "Actuary",
      "Acupuncturist",
      "Administration Manager",
      "Admissions Clerk",
      "Advertising and Marketing Professional",
      "Advertising Manager",
      "Advertising Specialist",
      "Advertising, Public Relations and Sales Manager",
      "Aerobics Instructor",
      "Aeronautical Engineer",
      "Aeroplane Pilot",
      "Aerospace Engineer",
      "Aged and Disabled Carer",
      "Agricultural and Forestry Scientist",
      "Agricultural and Horticultural Mobile Plant Operator",
      "Agricultural Consultant",
      "Agricultural Engineer",
      "Agricultural Scientist",
      "Agricultural Technician",
      "Agricultural, Forestry & Horticultural Operator",
      "Agronomist",
      "Air Traffic Controller",
      "Air Transport Professional",
      "Airconditioning and Mechanical Services Plumber",
      "Airconditioning and Refrigeration Mechanic",
      "Aircraft Baggage Handler and Airline Ground Crew",
      "Aircraft Maintenance Engineer",
      "Aircraft Maintenance Engineer (Avionics)",
      "Aircraft Maintenance Engineer (Mechanical)",
      "Aircraft Maintenance Engineer (Structures)",
      "Aircraft Refueller",
      "Alarm, Security and Surveillance Monitor",
      "Alternative Health Therapist",
      "Ambulance Officer",
      "Ambulance Officer and Paramedic",
      "Amusement Centre Manager",
      "Amusement, Fitness and Sports Centre Manager",
      "Anaesthetic Technician",
      "Anaesthetist",
      "Analyst Programmer",
      "Animal Attendant and Trainer",
      "Anthropologist (Other Social Professional)",
      "Antique Dealer",
      "Apiarist",
      "Apparel Cutter",
      "Applications Developer",
      "Aquaculture Farmer",
      "Aquaculture Worker",
      "Arborist",
      "Archaeologist",
      "Architect",
      "Architect (Landscape)",
      "Architectural Draftsperson",
      "Architectural, Building & Surveying Technician",
      "Archivist",
      "Archivist, Curator and Records Manager",
      "Armoured Car Escort",
      "Art Director (Film, Television or Stage)",
      "Art Teacher (Private Tuition)",
      "Artistic Director",
      "Artistic Director, Media Producer & Presenter",
      "Arts Administrator and Manager",
      "Assembly Worker",
      "Assistant in Nursing",
      "Astronomer (Physicist)",
      "Athlete",
      "Auctioneer",
      "Auctioneer, and Stock and Station Agent",
      "Audiologist",
      "Audiologist and Speech Pathologist",
      "Audiometrist (Other Medical Technician)",
      "Audiovisual Technician (Electronic Equipment Trades Worker)",
      "Auditor, Company Secretary and Corporate Treasurer",
      "Australian Rules Footballer",
      "Author",
      "Author, and Book and Script Editor",
      "Autoglazier",
      "Automobile Driver",
      "Automotive Electrician",

      "Backhoe Operator",
      "Baker",
      "Baker and Pastrycook",
      "Bakery Assistant",
      "Baking Factory Worker",
      "Bank Manager and Branch Manager",
      "Bank Teller",
      "Bank Worker",
      "Bar Attendant",
      "Bar Attendant and Barista",
      "Bar Useful and Busser",
      "Barber",
      "Barista",
      "Barrister",
      "Beauty Therapist",
      "Bed and Breakfast Operator",
      "Beef Cattle Farm Worker",
      "Beef Cattle Farmer",
      "Beekeeper",
      "Betting Agency Counter Clerk",
      "Betting Agency Manager",
      "Betting Clerk",
      "Bicycle Mechanic",
      "Binders, Finisher and Screen Printer",
      "Biochemist",
      "Biologist",
      "Biomedical Engineer",
      "Biotechnologist",
      "Blacksmith",
      "Blasting Worker",
      "Blogger, Critic, Sports and Other Writer",
      "Blood Collector (Pathology Collector)",
      "Boarding Kennel and Cattery Operator",
      "Boat Builder and Repairer",
      "Boat Builder and Shipwright",
      "Body Artist",
      "Boiler and Engine Operator",
      "Boilermaker",
      "Boilermaker's Assistant",
      "Boner and Slicer",
      "Book and Script Editor",
      "Bookkeeper",
      "Bookmaker",
      "Bookmaker's Clerk",
      "Botanist",
      "Bouncer",
      "Branch Manager (Financial Services)",
      "Brewery Worker",
      "Bricklayer",
      "Bricklayer and Stonemason",
      "Bricklayer's Assistant",
      "Broadcast Transmitter Operator",
      "Broker (Financial)",
      "Builder's Labourer",
      "Building and Construction Manager",
      "Building and Engineering Technician",
      "Building and Plumbing Labourer",
      "Building Associate",
      "Building Certifier",
      "Building Economist",
      "Building Estimator",
      "Building Inspector",
      "Building Insulation Installer",
      "Building Manager",
      "Building Surveyor",
      "Building Technician",
      "Bulk Materials Handling Plant Operator",
      "Bulldozer Operator",
      "Bungy Jump Master",
      "Bus and Coach Driver",
      "Bus Driver",
      "Business Analyst (ICT)",
      "Business Broker",
      "Business Machine Mechanic",
      "Business Manager",
      "Business Owner",
      "Business Services Manager",
      "Butchers and Smallgoods Maker",
      "Buyer (Retail and Wool)",
      
      "Cabin Crew",
      "Cabinetmaker",
      "Cabler (Data and Telecommunications)",
      "Cafe and Restaurant Manager",
      "Cafe Worker",
      "Cake Decorator (Pastrycook)",
      "Call Centre or Contact Centre Manager",
      "Call Centre or Contact Centre Operator",
      "Call Centre or Contact Centre Team Leader",
      "Call or Contact Centre Workers",
      "Call, Contact Centre & Customer Service Manager",
      "Camera Operator (Film, Television or Video)",
      "Canvas and Leather Goods Maker",
      "Canvas Goods Fabricator",
      "Car Detailer",
      "Car Mechanic",
      "Car Park Attendant",
      "Car Parts & Accessories Fitter",
      "Car Salesperson",
      "Caravan Park and Camping Ground Manager",
      "Cardiac Technician",
      "Cardiologist",
      "Cardiothoracic Surgeon",
      "Careers Adviser",
      "Careers Counsellor",
      "Carer (Aged and Disabled)",
      "Carer (Children)",
      "Caretaker",
      "Carpenter",
      "Carpenter and Joiner",
      "Carpenter's Assistant",
      "Carpet Cleaner",
      "Carpet Layer",
      "Cartographer",
      "Cash Van Salesperson",
      "Cashier",
      "Cement and Concrete Plant Worker",
      "Cement Production Plant Operator",
      "Certifier (Building)",
      "Charter and Tour Bus Driver",
      "Chauffeur",
      "Checkout Operator",
      "Checkout Operator and Office Cashier",
      "Checkout Supervisor",
      "Cheese Maker",
      "Chef",
      "Chemical and Materials Engineer",
      "Chemical Engineer",
      "Chemical Plant Operator",
      "Chemical Plant Worker",
      "Chemical Production Machine Operator",
      "Chemical, Gas, Petroleum & Power Plant Operator",
      "Chemistry Technician",
      "Chemist",
      "Chemist, and Food and Wine Scientist",
      "Chief Executive and Managing Director",
      "Chief Financial Officer",
      "Chief Information Officer",
      "Chief Operating Officer",
      "Child and Youth Residential Care Assistant",
      "Child Care Centre Manager",
      "Child Care Worker",
      "Child Carer",
      "Chinese Medicine Practitioner",
      "Chiropractor",
      "Chiropractor and Osteopath",
      "Chocolate Packer",
      "Choreographer",
      "Cinema and Theatre Manager",
      "Cinematographer",
      "Civil Celebrant",
      "Civil Engineering Draftsperson",
      "Civil Engineering Draftsperson and Technician",
      "Civil Engineering Professional",
      "Civil Engineering Technician",
      "Civil Engineer",
      "Classified Advertising Clerk",
      "Clay Processing Factory Worker",
      "Clay Products Machine Operator",
      "Clay, Concrete, Glass & Stone Machine Operator",
      "Cleaner (Commercial)",
      "Cleaner (Domestic)",
      "Cleaner",
      "Clerical and Administrative Worker",
      "Clerical and Office Support Worker",
      "Clerk (Accounting)",
      "Clerk (Betting)",
      "Clerk (Court and Legal)",
      "Clerk (Filing and Registry)",
      "Clerk (General)",
      "Clerk (Human Resource)",
      "Clerk (Inquiry)",
      "Clerk (Insurance, Money Market and Statistical)",
      "Clerk (Payroll)",
      "Clerk (Purchasing and Supply Logistics)",
      "Clerk (Transport and Despatch)",
      "Clerk of Court",
      "Climatologist (Meteorologist)",
      "Clinical Coder",
      "Clinical Haematologist",
      "Clinical Psychologist",
      "Clothing Patternmaker",
      "Clothing Trades Worker",
      "Club Manager",
      "Coache (Sports)",
      "Commercial Cleaner",
      "Commercial Housekeeper",
      "Commissioned Defence Force Officer",
      "Commissioned Fire Officer",
      "Commissioned Officer (Management)",
      "Commissioned Police Officer",
      "Commodities Trader",
      "Communications Manager",
      "Communications Operator",
      "Communications Technician",
      "Communications Trades Worker",
      "Community Arts Worker",
      "Community Health Worker",
      "Community Worker",
      "Company Secretary",
      "Complementary Health Therapist",
      "Composer",
      "Computer Network and Systems Engineer",
      "Computer Network Professional",
      "Concierges (Hotel Service Manager)",
      "Concrete Batching Plant Operator",
      "Concrete Products Machine Operator",
      "Concrete Pump Operator",
      "Concreter",
      "Conductor (Transport)",
      "Confectionery Maker",
      "Conference and Event Organiser",
      "Conservation Officer",
      "Conservator",
      "Construction Estimator",
      "Construction Manager",
      "Construction Plant Operator",
      "Construction Project Manager",
      "Construction Rigger",
      "Construction Worker",
      "Container Filler",
      "Contract Administrator",
      "Contract, Program and Project Administrator",
      "Conveyancer",
      "Conveyancer and Legal Executive",
      "Cook",
      "Cook (Fast Food)",
      "Copywriter",
      "Coremaker",
      "Corporate General Manager",
      "Corporate Services Manager",
      "Corporate Treasurer",
      "Correctional Officer",
      "Cost Clerk",
      "Costume Designer (Fashion Designer)",
      "Cotton Grower",
      "Councillor",
      "Counselling Psychologist (Other Psychologist)",
      "Counsellor",
      "Courier",
      "Courier and Postal Deliverer",
      "Court and Legal Clerk",
      "Court Bailiff and Sheriff",
      "Court Clerk",
      "Court Orderly",
      "Crane Chaser",
      "Crane, Hoist and Lift Operator",
      "Creative Director (Advertising)",
      "Credit and Loans Officer",
      "Criminologist (Other Social Professional)",
      "Crop Farm Worker",
      "Crop Farmer",
      "Crossing Supervisor",
      "Croupier",
      "Crowd Controller",
      "Curator",
      "Customer Service Manager",
      "Customs Broker",
      "Customs Officer",
      
      "Dairy Cattle Farm Workers",
      "Dairy Cattle Farmers",
      "Dairy Products Makers",
      "Dance Teachers (Private Tuition)",
      "Dancers and Choreographers",
      "Data Entry Operators",
      "Database & Systems Administrators & ICT Security",
      "Database Administrators",
      "Dealers (Financial)",
      "Debt Collectors",
      "Deck and Fishing Hands",
      "Deck Hands",
      "Deck Officers",
      "Deer Farmers",
      "Defence Force Members - Other Ranks",
      "Defence Force Senior Officers",
      "Delivery Drivers",
      "Demonstrators (Sales)",
      "Dental Assistants",
      "Dental Hygienists",
      "Dental Hygienists, Technicians and Therapists",
      "Dental Practitioners",
      "Dental Prosthetists",
      "Dental Specialists (including Orthodontists)",
      "Dental Technicians",
      "Dental Therapists",
      "Dentists",
      "Dermatologists",
      "Designers (Fashion, Industrial and Jewellery)",
      "Designers (Graphic and Web)",
      "Designers (Interior)",
      "Despatch Clerks",
      "Despatching and Receiving Clerks",
      "Detailers",
      "Detectives",
      "Developer Programmers",
      "Development Managers",
      "Diagnostic and Interventional Radiologists",
      "Die Setters",
      "Diesel Motor Mechanics",
      "Dietitians",
      "Directors (Child Care)",
      "Directors (Film, Television, Radio or Stage)",
      "Directors of Nursing",
      "Disabilities Services Officers",
      "Disabled Carers",
      "Disk Jockeys (Nightclub)",
      "Disk Jockeys (Radio)",
      "Dispensary Technicians",
      "Divers",
      "Diversional Therapists",
      "Doctors (Generalists)",
      "Dog and Horse Racing Officials",
      "Dog Handlers and Trainers",
      "Dogmen (Crane Chasers)",
      "Domestic Cleaners",
      "Domestic Housekeepers",
      "Doorpersons and Luggage Porters",
      "Door-to-door Salespersons",
      "Draftspersons (Civil Engineering)",
      "Draftspersons (Electrical Engineering )",
      "Draftspersons (Electronic Engineering )",
      "Draftspersons (Mechanical Engineering )",
      "Drainage, Sewerage and Stormwater Labourers",
      "Drainers",
      "Drama Teachers (Private Tuition)",
      "Dressmakers and Tailors",
      "Drillers",
      "Driller's Assistants",
      "Drillers, Miners and Shot Firers",
      "Drivers (Automobile)",
      "Drivers (Bus and Coach)",
      "Drivers (Delivery)",
      "Drivers (Forklift)",
      "Drivers (Train and Tram)",
      "Drivers (Truck)",
      "Driveway Attendants",
      "Driving Instructors",
      "Drug and Alcohol Counsellors",
      "Drycleaners",
      
      "Ear, Nose and Throat Specialists",
      "Early Childhood (Pre-primary School) Teachers",
      "Earth Science Technicians",
      "Earthmoving Labourers",
      "Earthmoving Plant Operators",
      "Earthmoving Plant Operators (General)",
      "Ecologists (Environmental Scientists)",
      "Economists",
      "Editors (Book and Script)",
      "Education Advisers",
      "Education Advisers and Reviewers",
      "Education Aides",
      "Education Managers (not covered elsewhere)",
      "Education Reviewers",
      "Educational Psychologists",
      "Electorate Officers",
      "Electrical and Telecommunications Trades Assistants",
      "Electrical Distribution Trades Workers",
      "Electrical Engineering Draftspersons",
      "Electrical Engineering Draftspersons, Technicians",
      "Electrical Engineering Technicians",
      "Electrical Engineers",
      "Electrical Linesworkers",
      "Electricians",
      "Electricians (General)",
      "Electricians (Special Class)",
      "Electronic Engineering Draftspersons",
      "Electronic Engineering Draftspersons, Technicians",
      "Electronic Engineering Technicians",
      "Electronic Equipment Trades Workers",
      "Electronic Instrument Trades Workers (General)",
      "Electronic Instrument Trades Workers (Special Class)",
      "Electronics Engineers",
      "Electronics Trades Workers",
      "Electroplaters",
      "Emergency Medicine Specialists",
      "Emergency Service Workers",
      "Employment Consultants",
      "Endocrinologists",
      "Engineering Managers",
      "Engineering Patternmakers",
      "Engineering Production Workers",
      "Engineering Professionals (not covered elsewhere)",
      "Engineering Technologists",
      "Engineers (Chemical and Material)",
      "Engineers (Civil)",
      "Engineers (Electrical)",
      "Engineers (Electronics)",
      "Engineers (Industrial, Mechanical & Production)",
      "Engineers (Mining)",
      "Engineers (Other)",
      "Engineers (Telecommunications)",
      "English as a Second Language Teachers",
      "Engravers",
      "Enrolled and Mothercraft Nurses",
      "Enrolled Nurses",
      "Entertainers and Variety Artists",
      "Entertainment Centre Managers",
      "Environmental Consultants",
      "Environmental Engineers",
      "Environmental Health Officers",
      "Environmental Managers",
      "Environmental Research Scientists",
      "Environmental Scientists",
      "Equipment Hire Managers",
      "Event Managers",
      "Event Organisers",
      "Examination Supervisors",
      "Excavator Operators",
      "Exercise Physiologists",
      "Exhaust and Muffler Repairers",
      "Exporters",
      "External Auditors",
      "Eye Specialists",
      "Eye Surgeon",
      
      "Fabric and Textile Factory Workers",
      "Facilities Administrators",
      "Facilities Managers",
      "Factory Process Workers (not covered elsewhere)",
      "Factory Workers (Food and Drink)",
      "Factory Workers (Plastics and Rubber)",
      "Faculty Heads",
      "Family and Marriage Counsellors",
      "Family Day Care Workers",
      "Family Support Workers",
      "Farm Workers (Crops)",
      "Farm Workers (Livestock)",
      "Farm Workers (Mixed Crop and Livestock)",
      "Farm, Forestry and Garden Workers (not covered elsewhere)",
      "Farmers (Aquaculture)",
      "Farmers (Crops)",
      "Farmers (Livestock)",
      "Farmers (Mixed Crop and Livestock)",
      "Farriers",
      "Fashion Designers",
      "Fashion, Industrial and Jewellery Designers",
      "Fast Food Cooks",
      "Fencers",
      "Fettlers",
      "Fibreglass Laminators",
      "Fibrous Plasterers",
      "Filing and Registry Clerks",
      "Film and Video Editors",
      "Film Producers",
      "Film, Television, Radio and Stage Directors",
      "Finance Brokers",
      "Finance Managers",
      "Financial Brokers",
      "Financial Controllers",
      "Financial Dealers",
      "Financial Institution Branch Manager",
      "Financial Investment Advisers",
      "Financial Investment Advisers and Managers",
      "Financial Investment Managers",
      "Financial Market Dealers",
      "Fire and Emergency Workers",
      "Fire Fighters",
      "Fire Protection Equipment Technicians",
      "First Aid Trainers",
      "Fisheries Officers",
      "Fishing Guides",
      "Fishing Hands",
      "Fitness Centre Managers",
      "Fitness Instructors",
      "Fitter and Turners",
      "Fitters (General)",
      "Fitter's Assistants",
      "Fitter-Welders",
      "Fleet Managers",
      "Flight Attendants",
      "Floor Finishers",
      "Floor Tilers",
      "Florists",
      "Flower Growers",
      "Flying Instructors",
      "Food and Beverage Attendants",
      "Food and Beverage Managers",
      "Food and Drink Factory Workers",
      "Food and Wine Scientists",
      "Food Scientists",
      "Food Technologists",
      "Food Trades Assistants",
      "Footballers (Soccer, Rugby and AFL)",
      "Footwear Factory Workers",
      "Footwear Production Machine Operators",
      "Forensic Psychologists (Clinical Psychologists)",
      "Forest Managers",
      "Foresters",
      "Forestry and Logging Workers",
      "Forestry Workers",
      "Forklift Drivers",
      "Freight and Furniture Handlers",
      "Freight Handlers (Rail or Road)",
      "Fruit and Nut Farm Workers",
      "Fruit and Nut Growers",
      "Fruit and Nut Pickers",
      "Fruit and Vegetable Factory Workers",
      "Fruit and Vegetable Packers",
      "Funeral Directors",
      "Funeral Workers",
      "Funeral Workers (Other)",
      "Furniture Finishers",
      "Furniture Removalist Drivers",
      "Furniture Removalist's Assistants",
      "Futures Traders",
      
      "Gallery and Museum Curators",
      "Gallery and Museum Guides",
      "Gallery and Museum Technicians",
      "Gallery, Library and Museum Technicians",
      "Gallery, Museum and Tour Guides",
      "Game and Multimedia Developers",
      "Game Developers (Electronic)",
      "Gaming Workers",
      "Garbage Collectors",
      "Garden and Nursery Labourers",
      "Garden Labourers",
      "Gardeners",
      "Gardeners (General)",
      "Gas and Petroleum Operators",
      "Gas Plant Operators",
      "Gasfitters",
      "Gastroenterologists",
      "General Clerks",
      "General Managers",
      "General Practitioners",
      "General Practitioners and Resident Medical Officers",
      "Genetic Counsellors (and Other Health Professionals not covered elsewhere)",
      "Geographer (Other Social Professionals)",
      "Geologists",
      "Geologists, Geophysicists and Hydrogeologists",
      "Geophysicists",
      "Geotechnical Engineers",
      "Glass Makers",
      "Glass Processing Workers",
      "Glass Production Machine Operators",
      "Glaziers",
      "Goat Farmers",
      "Golfers",
      "Grader Operators",
      "Grain Mill Workers",
      "Grain, Oilseed and Pasture Farm Workers",
      "Grain, Oilseed and Pasture Growers",
      "Grape Growers",
      "Graphic and Web Designers, and Illustrators",
      "Graphic Designers",
      "Graphic Pre-press Trades Workers",
      "Greenkeepers",
      "Group Leaders (Child Care)",
      "Guides (Outdoor Adventure)",
      "Gunsmiths",
      "Gymnastics Coaches and Instructors",
      "Gynaecologist and Obstetricians",
      
      "Hair and Beauty Salon Assistants",
      "Hair and Beauty Salon Managers",
      "Hairdressers",
      "Handypersons",
      "Hardware Technicians",
      "Health and Welfare Services Managers",
      "Health Diagnostic and Promotion Professionals (not covered elsewhere)",
      "Health Educator",
      "Health Information Managers",
      "Health Practice Managers",
      "Health Promotion Officers",
      "Helicopter Pilots",
      "Herbalists (Western)",
      "Hide and Skin Processing Machine Operators",
      "Hide and Skin Processing Workers",
      "High School Teacher (Secondary School)",
      "Historians",
      "Home Improvement Installers",
      "Homoeopaths",
      "Horse Breeders",
      "Horse Riding Coaches and Instructors",
      "Horse Trainers",
      "Horticultural Nursery Assistant",
      "Hospital orderlies",
      "Hospital Pharmacists",
      "Hospital Ward Clerks",
      "Hospitality Workers (not covered elsewhere)",
      "Hospitality, Retail and Service Managers (not covered elsewhere)",
      "Hostel Parents",
      "Hotel and Motel Managers",
      "Hotel and Motel Receptionists",
      "Hotel Service Managers",
      "Housekeepers",
      "Human Resource Advisers",
      "Human Resource Clerks",
      "Human Resource Managers",
      "Human Resource Professionals",
      "Hunter-Trappers",
      "Hunting Guides",
      "Hydrogeologists",
      "Hydrographers",
      
      "ICT Account Managers",
      "ICT Business Analysts",
      "ICT Business and Systems Analysts",
      "ICT Business Development Managers",
      "ICT Customer Support Officers",
      "ICT Managers",
      "ICT Project Managers",
      "ICT Quality Assurance Engineers",
      "ICT Sales Assistants",
      "ICT Sales Professionals",
      "ICT Sales Representatives",
      "ICT Security Specialists",
      "ICT Support and Test Engineers",
      "ICT Support Engineers",
      "ICT Support Technicians",
      "ICT Systems Test Engineers",
      "ICT Trainers",
      "Illustrators (including Animators)",
      "Immigration Officers",
      "Importers and Exporters",
      "Importers, Exporters and Wholesalers",
      "Import-Export Clerks",
      "Indigenous Health Workers",
      "Industrial Designers",
      "Industrial Engineers",
      "Industrial Pharmacists",
      "Industrial Psychologist",
      "Industrial Spraypainters",
      "Industrial, Mechanical and Production Engineers",
      "Information and Organisation Professionals (not covered elsewhere)",
      "Information Officers",
      "Inspectors and Regulatory Officers",
      "Insulation and Home Improvement Installers",
      "Insurance Agents",
      "Insurance Brokers",
      "Insurance Consultants",
      "Insurance Investigators",
      "Insurance Investigators, Loss Adjusters and Risk Surveyors",
      "Insurance Loss Adjusters",
      "Insurance Risk Surveyors",
      "Insurance, Money Market and Statistical Clerks",
      "Integration Aides",
      "Intellectual Property Lawyers",
      "Intelligence and Policy Analysts",
      "Intelligence Officers",
      "Intensive Care Ambulance Paramedics",
      "Intensive Care Specialists",
      "Interior Decorators",
      "Interior Designers",
      "Internal Auditors",
      "Interpreters",
      "Interviewers (Surveys)",
      "Investment Advisers",
      "Ironers and Pressers",
      
      "Janitors",
      "Jewellers",
      "Jewellery Designers",
      "Jockeys",
      "Joiners",
      "Journalists and Other Writers",
      "Judges",
      "Judicial and Other Legal Professionals",
      "Judicial and Other Legal Professionals (not covered elsewhere)",
      
      "Kennel Hands",
      "Keyboard Operators",
      "Kindergarten Teachers (Early Childhood)",
      "Kitchenhands",
      "Knitting Machine Operators",
      
      "Laboratory Managers",
      "Labourers (Building and Plumbing)",
      "Labourers (Garden and Nursery)",
      "Labourers (not covered elsewhere)",
      "Labourers (Paving and Surfacing)",
      "Labourers (Railway)",
      "Laggers",
      "Land Economists",
      "Land Economists and Valuers",
      "Landscape Architects",
      "Landscape Gardeners",
      "Laundry Workers",
      "Laundry Workers (General)",
      "Law Clerks",
      "Lawn Mowers",
      "Leaflet and Newspaper Deliverers",
      "Leather Goods Makers",
      "Lecturers and Tutors (University)",
      "Legal Clerks",
      "Legal Executives",
      "Legal Secretaries",
      "Legislators",
      "Liaison Officers",
      "Librarians",
      "Library Assistants",
      "Library Technicians",
      "Licensed Club Managers",
      "Life Science Technicians",
      "Life Scientists",
      "Lifeguards",
      "Lift Mechanics",
      "Light Technicians",
      "Linemarkers",
      "Linesmen",
      "Linespersons (Electrical)",
      "Linespersons (Telecommunications)",
      "Linguist (Other Social Professionals)",
      "Livestock Farm Workers",
      "Livestock Farmers",
      "Loader Operators",
      "Loans Officers",
      "Local Government Legislators",
      "Locksmiths",
      "Logging Assistants",
      "Logging Plant Operators",
      "Logistics Clerks (Production Clerks)",
      "Logistics Managers",
      "Loss Adjusters",
      "Lotteries Agents",
      
      "Machine Operators (Clay, Concrete, Glass & Stone)",
      "Machine Operators (not covered elsewhere)",
      "Machine Operators (Paper and Wood Processing)",
      "Machine Operators (Plastics and Rubber Production)",
      "Machine Operators (Textile & Footwear Production)",
      "Machine Shorthand Reporters",
      "Machinists (Metal)",
      "Machinists (Sewing)",
      "Machinists (Wood)",
      "Magistrates",
      "Mail Clerks",
      "Mail Sorters",
      "Maintenance Fitters (Fitters)",
      "Maintenance Planners",
      "Make Up Artists",
      "Management Accountants",
      "Management and Organisation Analysts",
      "Management Consultants",
      "Managers (Advertising and Sales)",
      "Managers (Amusement, Fitness and Sports Centre)",
      "Managers (Cafe and Restaurant)",
      "Managers (Caravan Park and Camping Ground)",
      "Managers (Child Care Centre)",
      "Managers (Construction)",
      "Managers (Corporate Services)",
      "Managers (Engineering)",
      "Managers (Finance)",
      "Managers (Health and Welfare Services)",
      "Managers (Hotel and Motel)",
      "Managers (Human Resources)",
      "Managers (ICT)",
      "Managers (Licenced Club)",
      "Managers (Non-school Education)",
      "Managers (Policy and Planning)",
      "Managers (Production)",
      "Managers (Research and Development)",
      "Managers (Retail)",
      "Managers (Supply and Distribution)",
      "Managers (Transport Services)",
      "Managing Directors",
      "Manufacturers",
      "Manufacturing Production Managers",
      "Marine Biologists",
      "Marine Engineers",
      "Marine Surveyors",
      "Marine Transport Professionals",
      "Market Research Analysts",
      "Marketing Managers",
      "Marketing Specialists",
      "Massage Therapists",
      "Master Fishers",
      "Materials Engineers",
      "Materials Recyclers",
      "Mathematicians",
      "Meat Boners and Slicers",
      "Meat Boners and Slicers, and Slaughterers",
      "Meat Inspectors",
      "Meat Packers",
      "Meat Process Workers",
      "Meat, Poultry and Seafood Process Workers",
      "Mechanical Engineering Draftspersons",
      "Mechanical Engineering Draftspersons, Technicians",
      "Mechanical Engineering Technicians",
      "Mechanical Engineers",
      "Mechanical Fitters (Fitters)",
      "Mechanic's Assistants",
      "Mechatronics Engineers (Engineering Professionals not covered elsewhere)",
      "Media Equipment Operators",
      "Media Producers",
      "Medical Administrators",
      "Medical Diagnostic Radiographers",
      "Medical Imaging Professionals",
      "Medical Imaging Technologist",
      "Medical Laboratory Scientists",
      "Medical Laboratory Technicians",
      "Medical Oncologists",
      "Medical Practitioners (Generalist)",
      "Medical Practitioners (not covered elsewhere)",
      "Medical Radiation Therapists",
      "Medical Receptionists",
      "Medical Records Administrators",
      "Medical Technicians",
      "Members of Parliament",
      "Merchandisers",
      "Metal Casting Trades Workers",
      "Metal Casting, Forging & Finishing Trades",
      "Metal Engineering Process Workers",
      "Metal Fabricators",
      "Metal Fitters and Machinists",
      "Metal Machinists (First Class)",
      "Metal Polishers",
      "Metallurgical and Materials Technicians",
      "Metallurgists",
      "Meteorologists",
      "Meter Readers",
      "Microbiologists",
      "Middle School Teachers",
      "Midwives",
      "Migration Agents",
      "Milliners",
      "Mine Deputys",
      "Mine Managers",
      "Miners",
      "Mining Engineer (excluding Petroleum)",
      "Mining Engineers",
      "Mining Support Workers",
      "Ministers of Religion",
      "Mixed Crop and Livestock Farm Workers",
      "Mixed Crop and Livestock Farmers",
      "Mixed Crop Farmers",
      "Mixed Livestock Farm Workers",
      "Mixed Livestock Farmers",
      "Mobile Plant Operators (not covered elsewhere)",
      "Models",
      "Models and Sales Demonstrators",
      "Money Market Clerks",
      "Mortgage Broker",
      "Morticians",
      "Motel Managers",
      "Mothercraft Nurses",
      "Motion Picture Projectionists",
      "Motor Mechanics",
      "Motor Mechanics (General)",
      "Motor Vehicle and Caravan Salespersons",
      "Motor Vehicle and Vehicle Parts Salespersons",
      "Motor Vehicle Licence Examiners",
      "Motor Vehicle Parts and Accessories Fitters",
      "Motor Vehicle Parts and Accessories Fitters (General)",
      "Motor Vehicle Parts Interpreters",
      "Motorcycle Mechanics",
      "Mountain and Glacier Guides",
      "Multimedia Designers",
      "Multimedia Developers",
      "Multimedia Specialists",
      "Multimedia Specialists and Web Developers",
      "Mushroom Pickers",
      "Music Directors",
      "Music Professionals",
      "Music Teachers (Private Tuition)",
      "Music, Dance, Drama, Play, Hypnotic, and Related Therapists",
      "Musical Instrument Makers and Repairers",
      "Musicians",
      "Mystery Shoppers",
      
      "Nail Technicians (Beauty Therapists)",
      "Nannies",
      "Natural and Physical Science Professionals (not covered elsewhere)",
      "Natural Remedy Consultants",
      "Naturopaths",
      "Naval Architects",
      "Network Administrators",
      "Network Analysts",
      "Neurologists",
      "Neuropsychologists (Clinical Psychologists)",
      "Neurosurgeons",
      "Newspaper and Periodical Editors",
      "Night Fillers",
      "Noxious Weeds and Pest Inspectors",
      "Nuclear Medicine Technologists",
      "Nurse Educators",
      "Nurse Educators and Researchers",
      "Nurse Managers",
      "Nurse Practitioners",
      "Nurse Researchers",
      "Nursery Hands (Horticulture)",
      "Nurserypersons",
      "Nurses (Dental)",
      "Nurses (Enrolled)",
      "Nurses (Registered)",
      "Nurses (Veterinary)",
      "Nursing Clinical Directors",
      "Nursing Support and Personal Care Workers",
      "Nursing Support Workers",
      "Nutrition Professionals",
      "Nutritionists",
      
      "Obstetricians and Gynaecologists",
      "Occupational & Environmental Health Professionals",
      "Occupational Health and Safety Advisers",
      "Occupational Psychologist",
      "Occupational Therapists",
      "Oenologists",
      "Office Equipment Technician",
      "Office Managers",
      "Oher Financial Dealers",
      "Oncologists (Medical)",
      "Oncologists (Radiation)",
      "Operating Room Nurses",
      "Operating Theatre Technicians",
      "Operators (Switchboard)",
      "Ophthalmologists",
      "Optical Dispensers",
      "Optical Mechanics",
      "Optometrists",
      "Optometrists and Orthoptists",
      "Oral Health Therapists (Dental Therapists)",
      "Order Clerks",
      "Orderlies (Hospital)",
      "Organisation and Methods Analysts",
      "Organisational Psychologists",
      "Orthopaedic Surgeons",
      "Orthoptists",
      "Orthotists and Prosthetists",
      "Osteopaths",
      "Other Accommodation and Hospitality Managers",
      "Other Actors, Dancers and Entertainers",
      "Other Air Transport Professionals",
      "Other Animal Attendants and Trainers",
      "Other Architectural, Building and Surveying Technicians",
      "Other Automobile Drivers",
      "Other Betting Clerks",
      "Other Building and Engineering Technicians",
      "Other Clay, Concrete, Glass and Stone Processing Machine Operators",
      "Other Cleaners",
      "Other Clerical & Administrative Workers",
      "Other Clerical and Office Support Workers",
      "Other Clothing Trades Workers",
      "Other Construction and Mining Labourers",
      "Other Counsellors and Life Coaches",
      "Other Crop Farm Workers",
      "Other Crop Farmers",
      "Other Education Managers",
      "Other Engineering Professionals",
      "Other Environmental Scientists",
      "Other Factory Process Workers",
      "Other Farm, Forestry and Garden Workers",
      "Other Film, Television, Radio and Stage Directors",
      "Other Financial Brokers",
      "Other Food and Drink Factory Workers",
      "Other Food Trades Assistants",
      "Other Health and Welfare Services Managers",
      "Other Health Diagnostic & Promotion Professionals",
      "Other Hospitality Workers",
      "Other Hospitality, Retail and Service Managers",
      "Other ICT Managers",
      "Other ICT Support and Test Engineers",
      "Other ICT Support Technicians",
      "Other Information and Organisation Professionals",
      "Other Inspectors and Regulatory Officers",
      "Other Legislators",
      "Other Life Scientists",
      "Other Livestock Farm Workers",
      "Other Livestock Farmers",
      "Other Machine Operators",
      "Other Marine Transport Professionals",
      "Other Medical Practitioners",
      "Other Medical Technicians",
      "Other Metal Fitters and Machinists",
      "Other Miscellaneous Labourers",
      "Other Mobile Plant Operators",
      "Other Music Professionals",
      "Other Natural and Physical Science Professionals",
      "Other Outdoor Adventure Guides",
      "Other Packers",
      "Other Performing Arts Technicians",
      "Other Personal Service Workers",
      "Other Plastics and Rubber Production Machine Operators",
      "Other Practice Managers",
      "Other Primary Products Inspectors",
      "Other Private Tutors and Teachers",
      "Other Psychologists",
      "Other Sales Assistants and Salespersons",
      "Other Sales Representatives",
      "Other Sales Support Workers",
      "Other Science Technicians",
      "Other Security Workers",
      "Other Social Professionals",
      "Other Software and Applications Programmers",
      "Other Spatial Scientists",
      "Other Special Education Teachers",
      "Other Specialist Managers",
      "Other Specialist Physicians",
      "Other Sports Coaches and Instructors",
      "Other Sports Officials",
      "Other Sportspersons",
      "Other Stationary Plant Operators",
      "Other Technical Sales Representatives",
      "Other Technicians and Trades Workers",
      "Other Textile and Footwear Production Machine Operators",
      "Other Travel Attendants",
      "Other Visual Arts or Crafts Professionals",
      "Other Wood Machinists and Wood Trades Workers",
      "Other Wood Processing Machine Operators",
      "Otorhinolaryngologists",
      "Out of School Hours Care Workers",
      "Outdoor Adventure Guides",
      "Outdoor Adventure Instructors",

      "Packers",
      "Paediatric Surgeons",
      "Paediatricians",
      "Painters (Visual Arts)",
      "Painting Trades Workers",
      "Panelbeaters",
      "Paper and Pulp Mill Operators",
      "Paper and Pulp Mill Workers",
      "Paper and Wood Processing Machine Operators",
      "Paper Products Machine Operators",
      "Paramedics (Ambulance)",
      "Park Rangers",
      "Parking Inspectors",
      "Parole and Probation Officers",
      "Passenger Coach Drivers",
      "Pastrycooks",
      "Pastrycook's Assistants",
      "Patent Attorneys (Intellectual Property Laywer)",
      "Patents Examiners",
      "Pathologists",
      "Pathology Collectors",
      "Patient Services Assistants",
      "Patternmakers (Clothing)",
      "Patternmakers (Engineering)",
      "Paving and Surfacing Labourers",
      "Paving Plant Operators",
      "Payroll Clerks",
      "Payroll Officers",
      "Performing Arts Technicians",
      "Personal Assistants",
      "Personal Care Assistants",
      "Personal Care Consultants",
      "Personal Care Workers",
      "Personal Service Workers (not covered elsewhere)",
      "Personal Trainers",
      "Personnel Managers",
      "Personnel Officers",
      "Pest Controllers",
      "Pet Groomers",
      "Petroleum Engineers",
      "Petroleum Plant Operators",
      "Pharmacists",
      "Pharmacy Sales Assistants",
      "Pharmacy Technicians",
      "Phlebotomists (Pathology Collectors)",
      "Photographers",
      "Photographer's Assistants",
      "Photographic Developers and Printers",
      "Physical Therapist",
      "Physicians",
      "Physicists (including Astronomers)",
      "Physiotherapists",
      "Piano Tuners",
      "Picture Framers",
      "Pig Farmers",
      "Pilots (Air Transport)",
      "Planners (Urban and Regional)",
      "Plant Mechanics (Fitters)",
      "Plant Operators (Agricultural, Forestry & Horticul",
      "Plant Operators (Earthmoving)",
      "Plant Operators (Other Mobile)",
      "Plant Operators (Stationary)",
      "Plasterers",
      "Plastic and Reconstructive Surgeons",
      "Plastic Cablemaking Machine Operators",
      "Plastic Compounding and Reclamation Machine Operators",
      "Plastic Surgeons",
      "Plastics and Rubber Factory Workers",
      "Plastics and Rubber Production Machine Operators",
      "Plastics Fabricators and Welders",
      "Plastics Factory Workers",
      "Plastics Production Machine Operators (General)",
      "Plastics Technicians",
      "Plumbers",
      "Plumbers (General)",
      "Plumber's Assistants",
      "Plumbing Inspectors",
      "Podiatrists",
      "Police",
      "Police Officers",
      "Policy Advisers",
      "Policy Analysts",
      "Policy and Planning Managers",
      "Political Scientist (Other Social Professionals)",
      "Porters",
      "Post Office Managers",
      "Postal Delivery Officers",
      "Postal Sorting Officers",
      "Potters and Ceramic Artists",
      "Poultry Farm Workers",
      "Poultry Farmers",
      "Poultry Process Workers",
      "Powder Monkeys",
      "Power Generation Plant Operators",
      "Practice Managers",
      "Precision Instrument Makers and Repairers",
      "Precision Metal Trades Workers",
      "Pre-press Trades Workers",
      "Preschool Aides",
      "Preschool Teachers (Early Childhood)",
      "Presenters",
      "Pressure Welders",
      "Primary Health Organisation Managers",
      "Primary Products Inspectors",
      "Primary School Teachers",
      "Principals (School)",
      "Print Finishers",
      "Print Journalists",
      "Printers",
      "Printer's Assistants",
      "Printing Assistants and Table Workers",
      "Printing Machinists",
      "Printing Table Workers",
      "Prison Officers",
      "Private Investigators",
      "Private Tutors and Teachers",
      "Probation Officers",
      "Process Workers (Meat, Poultry and Seafood)",
      "Process Workers (Metal Engineering)",
      "Process Workers (Other Factory)",
      "Process Workers (Timber and Wood)",
      "Procurement Managers",
      "Procurement Officers",
      "Producers (Media)",
      "Product Assemblers",
      "Product Designers (Industrial)",
      "Product Examiners",
      "Product Graders",
      "Product Quality Controllers",
      "Product Testers",
      "Production and Plant Engineers",
      "Production Assistants (Film, Television, Radio or Stage)",
      "Production Clerks",
      "Production Managers",
      "Production Managers (Forestry)",
      "Production Managers (Mining)",
      "Production Recording Clerks",
      "Production Systems Workers (Engineering)",
      "Program Administrators",
      "Program and Project Administrators",
      "Program Directors (Television or Radio)",
      "Programmers",
      "Project Administrators",
      "Project Builders",
      "Project Coordinators",
      "Proof Readers",
      "Property Managers",
      "Property Valuers",
      "Prosthetists or Orthotists",
      "Psychiatric Nurse",
      "Psychiatrists",
      "Psychologists and Psychotherapists",
      "Psychotherapists",
      "Public Relations Managers",
      "Public Relations Professionals",
      "Purchasing and Supply Logistics Clerks",
      "Purchasing Officers",
      
      "Quality Assurance Assessors",
      "Quality Assurance Managers",
      "Quality Control Assessors",
      "Quantity Surveyors",
      "Quarantine Officers",
      
      "Radiation Oncologists",
      "Radiation Therapists (Medical)",
      "Radiator Repairers",
      "Radio Despatchers",
      "Radio Journalists",
      "Radio Presenters",
      "Radiocommunications Technicians",
      "Radiographers",
      "Railway Signal Operators",
      "Railway Station Managers",
      "Railway Track Plant Operators",
      "Railway Track Workers",
      "Railways Assistants",
      "Rangers",
      "Real Estate Agency Principals",
      "Real Estate Agents",
      "Real Estate Representatives",
      "Real Estate Sales Agents",
      "Receptionists",
      "Receptionists (General)",
      "Records Managers",
      "Recreation Officers",
      "Recreational Therapists",
      "Recruitment Consultants",
      "Recycling and Rubbish Collectors",
      "Recycling Workers",
      "Referees (Sports)",
      "Refrigeration Mechanics",
      "Refuge Workers",
      "Regional Education Managers",
      "Registered Nurses",
      "Registered Nurses (Aged Care)",
      "Registered Nurses (Child and Family Health)",
      "Registered Nurses (Community Health)",
      "Registered Nurses (Critical Care and Emergency)",
      "Registered Nurses (Developmental Disability)",
      "Registered Nurses (Disability and Rehabilitation)",
      "Registered Nurses (Medical Practice)",
      "Registered Nurses (Medical)",
      "Registered Nurses (Mental Health)",
      "Registered Nurses (not covered elsewhere)",
      "Registered Nurses (Paediatrics)",
      "Registered Nurses (Perioperative)",
      "Registered Nurses (Surgical)",
      "Regulatory Officers",
      "Rehabilitation Counsellors",
      "Reinforced Plastic and Composite Production Workers",
      "Religious Assistants",
      "Renal Medicine Specialists",
      "Rental Salespersons",
      "Research and Development Managers",
      "Resident Medical Officers",
      "Residential Care Officers",
      "Respiratory Medicine Physicians",
      "Restaurant Managers",
      "Retail and Wool Buyers",
      "Retail Assistants",
      "Retail Buyers",
      "Retail Loss Prevention Officers",
      "Retail Managers",
      "Retail Managers (General)",
      "Retail Pharmacists",
      "Retail Supervisors",
      "Retirement Village Managers",
      "Rheumatologists",
      "Riggers (Construction)",
      "Road Roller Operators",
      "Road Traffic Controllers",
      "Roof Plumbers",
      "Roof Tilers",
      "Rubber Factory Workers",
      "Rubber Production Machine Operators",
      "Rugby League Footballers",
      "Rugby Union Footballers",

      "Safety Inspectors",
      "Sail Makers",
      "Sales Agents (Real Estate)",
      "Sales and Marketing Managers",
      "Sales Assistants (General)",
      "Sales Assistants (ICT)",
      "Sales Assistants (Pharmacy)",
      "Sales Assistants and Salespersons (not covered elsewhere)",
      "Sales Demonstrators",
      "Sales Managers",
      "Sales Professionals (ICT)",
      "Sales Representatives",
      "Sales Representatives (Building and Plumbing Supplies)",
      "Sales Representatives (Business Services)",
      "Sales Representatives (Industrial Products)",
      "Sales Representatives (Medical and Pharmaceutical Products)",
      "Sales Representatives (Motor Vehicle Parts and Accessories)",
      "Sales Representatives (Personal and Household Goods)",
      "Sales Representatives (Technical)",
      "Salespersons (Motor Vehicle and Vehicle Parts)",
      "Salespersons (Tickets)",
      "Sand Blasters",
      "Saw Doctors",
      "Sawmill and Timber Yard Workers",
      "Sawmilling Operators",
      "Scaffolders",
      "School Cleaners (Commercial Cleaners)",
      "School Counsellor",
      "School Laboratory Technicians",
      "School Principals",
      "Science Technicians",
      "Screen Printers",
      "Scuba, Snorkelling and Dive instructors",
      "Sculptors",
      "Seafood Packers",
      "Seafood Process Workers",
      "Secondary School Teachers",
      "Secretaries",
      "Secretaries (General)",
      "Security Consultants",
      "Security Officers",
      "Security Officers and Guards",
      "Security Specialists (ICT)",
      "Security Technicians (Electronic Equipment Trades Workers)",
      "Senior Non-Commissioned Defence Force Officers",
      "Service Station Attendants",
      "Sewing Machinists",
      "Shearers",
      "Shearing Shed Hands",
      "Sheep Farm Workers",
      "Sheep Farmers",
      "Sheetmetal Trades Workers",
      "Shelf Fillers",
      "Ship's Captains",
      "Ship's Engineers",
      "Ship's Masters",
      "Ship's Officers",
      "Shipwrights",
      "Shoemakers",
      "Shop Managers",
      "Shopfitters (Carpenter and Joiners)",
      "Short Order Cooks",
      "Shot Firers",
      "Sign Erectors",
      "Signwriters",
      "Singers",
      "Slaughterers",
      "Small Engine Mechanics",
      "Small Offset Printers",
      "Smallgoods Makers",
      "Snowsport Instructors",
      "Soccer Players (Footballers)",
      "Social Professionals",
      "Social Security Assessors",
      "Social Workers",
      "Sociologist (Other Social Professionals)",
      "Software and Applications Programmers",
      "Software Developers (in Developer Programmers)",
      "Software Engineers",
      "Software Testers",
      "Soil Scientists",
      "Solicitors",
      "Solid Plasterers",
      "Sonographers",
      "Sound Technicians",
      "Sous Chefs (Chefs)",
      "Spare Parts Interpreters",
      "Special Care Workers",
      "Special Education Teachers",
      "Special Needs Teachers",
      "Specialist Managers (not covered elsewhere)",
      "Specialist Physicians",
      "Specialist Physicians (General Medicine)",
      "Specimen Collectors",
      "Speech Pathologists",
      "Speech Therapist",
      "Sport Psychologists (Other Psychologists)",
      "Sports Administrators",
      "Sports Centre Managers",
      "Sports Coaches, Instructors and Officials",
      "Sports Development Officers",
      "Sports Physiotherapists",
      "Sports Umpires",
      "Sportspersons",
      "Spraypainters (Industrial)",
      "Spraypainters (Vehicle)",
      "Stablehands",
      "Stage Managers",
      "Stationary Plant Operators (not covered elsewhere)",
      "Statistical Clerks",
      "Statisticians",
      "Steel Fixers",
      "Sterilisation Technicians",
      "Stevedores",
      "Stock and Station Agents",
      "Stock Clerks",
      "Stockbrokers",
      "Stone Processing Machine Operators",
      "Stonemasons",
      "Store Detectives",
      "Storepersons",
      "Street Vendors",
      "Street Vendors and Related Salespersons",
      "Streetsweeper Operators",
      "Structural Engineers",
      "Structural Steel and Welding Trades Workers",
      "Structural Steel Construction Workers",
      "Structural Steel Erectors",
      "Student Counsellors",
      "Sugar Cane Growers",
      "Sugar Mill Workers",
      "Supervisors (Retail)",
      "Supply and Distribution Managers",
      "Supply Chain Managers",
      "Supply, Distribution and Procurement Managers",
      "Surgeons",
      "Surgeons (General)",
      "Survey Interviewers",
      "Surveying and Spatial Science Technicians",
      "Surveyors",
      "Surveyors and Spatial Scientists",
      "Surveyor's Assistants",
      "Swimming Coaches and Instructors",
      "Switchboard Operators",
      "Systems Administrators",
      "Systems Analysts",
      
      "TAFE Teacher",
      "Tailors",
      "Tanker Drivers",
      "Tattoo Artists (Body Artists)",
      "Taxation Accountants",
      "Taxation Inspectors",
      "Taxi Drivers",
      "Teachers (Early Childhood)",
      "Teachers (Middle School)",
      "Teachers (Primary School)",
      "Teachers (Private)",
      "Teachers (Secondary School)",
      "Teachers (Special Education)",
      "Teachers (Vocational Education)",
      "Teachers' Aides",
      "Teachers of English to Speakers of Other Languages",
      "Teachers of the Hearing Impaired",
      "Teachers of the Sight Impaired",
      "Technical Cable Jointers",
      "Technical Directors",
      "Technical Sales Representatives",
      "Technical Writers",
      "Technicians (Agricultural)",
      "Technicians (Architectural, Building & Surveying)",
      "Technicians (Civil Engineering)",
      "Technicians (Dental)",
      "Technicians (Electrical Engineering)",
      "Technicians (Electronic Engineering)",
      "Technicians (Gallery, Library and Museum)",
      "Technicians (ICT Support)",
      "Technicians (Mechanical Engineering)",
      "Technicians (Medical)",
      "Technicians (Other Building and Engineering)",
      "Technicians (Performing Arts)",
      "Technicians (Science)",
      "Technicians and Trades Workers (not covered elsewhere)",
      "Telecommunications Cable Jointers",
      "Telecommunications Engineering Professionals",
      "Telecommunications Engineers",
      "Telecommunications Field Engineers",
      "Telecommunications Linesworkers",
      "Telecommunications Network Engineers",
      "Telecommunications Network Planners",
      "Telecommunications Technical Officers and Technologists",
      "Telecommunications Technical Specialists",
      "Telecommunications Technicians",
      "Telecommunications Trades Workers",
      "Telemarketers",
      "Telephone Betting Clerks",
      "Telephone Operators",
      "Television Equipment Operators",
      "Television Journalists",
      "Television Presenters",
      "Tennis Coaches",
      "Test Analysts (ICT)",
      "Textile & Footwear Production Machine Operators",
      "Textile Dyeing and Finishing Machine Operators",
      "Textile, Clothing and Footwear Mechanics",
      "Therapy Aides",
      "Thoracic Medicine Specialists",
      "Ticket Collectors and Ushers",
      "Ticket Salespersons",
      "Ticket Sellers",
      "Tilers (Floor)",
      "Tilers (Roof)",
      "Tiler's Assistants",
      "Timber and Wood Process Workers",
      "Toolmakers",
      "Toolmakers and Engineering Patternmakers",
      "Tour Guides",
      "Tourism and Travel Advisers",
      "Tourist Information Officers",
      "Tow Truck Drivers",
      "Train and Tram Drivers",
      "Train Controllers",
      "Train Drivers",
      "Train Examiners",
      "Trainers (Animal)",
      "Trainers (ICT)",
      "Training and Development Professionals",
      "Tram Drivers",
      "Translators",
      "Transport and Despatch Clerks",
      "Transport Company Managers",
      "Transport Conductors",
      "Transport Engineers",
      "Transport Operations Inspectors",
      "Transport Services Managers",
      "Travel Agency Managers",
      "Travel Agents",
      "Travel Attendants",
      "Travel Consultants",
      "Tree Fallers",
      "Tree Surgeons",
      "Trekking Guides",
      "Tribunal Members",
      "Trimmers (Vehicle)",
      "Trolley Collectors",
      "Truck Drivers",
      "Truck Drivers (General)",
      "Truck Driver's Offsiders",
      "Trust Officers",
      "Turf Growers",
      "Tutors and Lecturers (University)",
      "Tutors and Teachers (Private)",
      "Typists",
      "Tyre Fitters",
      
      "Undertakers",
      "Undertakers",
      "University Lecturers",
      "University Lecturers and Tutors",
      "University Tutors",
      "Upholsterers",
      "Urban and Regional Planners",
      "Urologists",
      "Ushers",
      
      "Valuers",
      "Vascular Surgeons",
      "Vegetable Farm Workers",
      "Vegetable Growers",
      "Vegetable Pickers",
      "Vehicle and Vehicle Parts Salespersons",
      "Vehicle Assemblers",
      "Vehicle Body Builders",
      "Vehicle Body Builders and Trimmers",
      "Vehicle Painters",
      "Vehicle Parts and Accessories Fitters",
      "Vehicle Trimmers",
      "Vending Machine Attendants",
      "Veterinarians",
      "Veterinary Nurses",
      "Video Editors",
      "Video Producers",
      "Vineyard Workers",
      "Visual Arts and Crafts Professionals",
      "Visual Merchandisers",
      "Vocalists",
      "Vocational Education Teachers",
      
      "Waiters",
      "Waitresses",
      "Wall and Floor Tilers",
      "Ward Clerks",
      "Wardspersons",
      "Warehouse Administrators",
      "Warehouse Assistants",
      "Waste Water and Water Plant Operators",
      "Watch and Clock Makers and Repairers",
      "Water Inspectors",
      "Waterside Workers",
      "Weaving Machine Operators",
      "Web Administrators",
      "Web Designers",
      "Web Developers",
      "Web Masters",
      "Weighbridge Operators",
      "Weight Loss Consultants",
      "Welders (First Class)",
      "Welfare Centre Managers",
      "Welfare Support Workers",
      "Welfare Workers",
      "Welfare, Recreation and Community Arts Workers",
      "Whitewater Rafting Guides",
      "Wholesalers",
      "Window Cleaners",
      "Window Dressers",
      "Wine Makers",
      "Winery Cellar Hands",
      "Wood and Wood Products Factory Workers",
      "Wood Machinists",
      "Wood Machinists and Other Wood Trades Workers",
      "Wood Processing Machine Operators",
      "Wood Turners",
      "Wool Buyers",
      "Wool Classers",
      "Wool Handlers",
      "Word Processing Operators",
      "Workplace Relations Advisers",
      "Writers (Authors)",
      "Writers (Journalists and Others)",
      
      "Yarn Carding and Spinning Machine Operators",
      "Youth Workers",
      
      "Zookeepers",
      "Zoologists"
    ],
    designJSONS = {
      "standard": [
        "ghost",
        "man",
        "woman",
        "boy",
        "girl",
        "monkey",
        "elephant",
        "deer",
        "horse",
        "cow",
        "sloth",
        "fox",
        "flying fox",
        "rhinoceros",
        "raccoon",
        "giraffe",
        "goat",
        "bat",
        "vampire bat",
        "megabat",
        "coyote",
        "otter",
        "sheep"
      ],
      "dogs":       [
        "dog",
        "labrador retriever",
        "pug",
        "siberian husky",
        "bulldog",
        "beagle",
        "pomeranian",
        "poodle",
        "chihuahua",
        "chow chow",
        "american pit bull terrier",
        "maltese",
        "boxer",
        "rottweiler",
        "golden tetriever",
        "dobermann",
        "shih tzu",
        "german shepherd",
        "yorkshire terrier",
        "great dane",
        "shiba ino",
        "dachshund",
        "french bulldog",
        "english mastiff",
        "samoyed dog",
        "shar pei",
        "pembroke welsh corgi",
        "greyhound",
        "st. bernard",
        "newfoundland dog",
        "jack russell terrier",
        "cavalier king charles spaniel",
        "american staffordshire terrier",
        "english cocker spaniel",
        "weimaraner",
        "american bully",
        "pekingese",
        "papillion",
        "bichon frise",
        "border collie",
        "west highland whiite terrier",
        "whippet",
        "austrialian shepherd",
        "sarabi mastiff",
        "pointer",
        "mexican hairless dog",
        "australian kelpie",
        "boston terrier",
        "cane corse",
        "akita",
        "bull terrier",
        "miniature pinscher"
      ],
      "felidae":    [
        "cat",
        "lion",
        "tiger",
        "leopard",
        "cheetah",
        "jaguar",
        "cougar",
        "wildcat",
        "lynx",
        "panther",
        "ocelot",
        "snow leopard",
        "caracal",
        "serval",
        "margay",
        "tigon",
        "jaguarundi",
        "leopard cat",
        "saber-toothed tiger",
        "clouded leopard",
        "palla",
        "oncilla",
        "jungle cat",
        "sand cat",
        "fishing cat",
        "rusty-spotted cat",
        "black-footed cat",
        "kodkod",
        "machairodontinae",
        "bay cat",
        "homotherium",
        "african golden cat",
        "asian golden cat",
        "pumapard",
        "puma",
        "machairodus",
        "andean mountain cat",
        "marbled cat",
        "flat-headed cat",
        "iriomote cat",
        "cat-fox",
        "siamese cat",
        "sphynx cat"
      ],
      "wolfs":      [
        "wolf",
        "arctic wolf",
        "northwestern wolf",
        "dingo",
        "japanese wolf",
        "eurasian wolf",
        "mexican wolf",
        "eastern wolf",
        "indian wolf",
        "italian wolf",
        "british columbia wolf",
        "hokkaido wolf",
        "great plains wolf",
        "tundra wolf",
        "interior Alaskan wolf",
        "arabian wolf",
        "alaskan tundra wolf"
      ],
      "bears":      [
        "bear",
        "polar bear",
        "brown bear",
        "american black bear",
        "asian black bear",
        "giant panda",
        "sloth bear",
        "spectacled bear",
        "kodiak bear",
        "eurasian brown bear",
        "tremarctos",
        "himalayan brown bear",
        "kamchatka brown bear",
        "kermode bear",
        "louisiana black bear",
        "alaska peninsula brown bear",
        "florida black bear",
        "california grizzly bear",
        "syrian brown bear",
        "glacier bear",
        "cinnamon bear",
        "ussuri brown bear",
        "tibetan blue bear",
        "pizzly",
        "formosan black bear",
        "siri lankan sloth bear",
        "mexican black bear",
        "balochistan black bear",
        "california black bear",
        "newfoundland black bear",
        "olympic black bear",
        "gobi bear",
        "new mexico black bear"
      ],
      "rodents":    [
        "rabbit",
        "squirrel",
        "mouse",
        "rat",
        "hampster",
        "beaver",
        "chinchilla",
        "gerbil",
        "coypu",
        "golpher",
        "agouti",
        "lemming",
        "dormouse",
        "cavies",
        "guinea pig",
        "degu",
        "blesmol",
        "paca",
        "hystricomorpha",
        "porcupine",
        "pedetes",
        "flying mouse",
        "flying squirrel"
      ],
      "birds":      [
        "hawk",
        "red-tailed hawk",
        "cooper's hawk",
        "eagle",
        "bald eagle",
        "golden eagle",
        "white-tailed eagle",
        "harpy eagle",
        "crowned eagle",
        "black eagle",
        "white-bellied sea eagle",
        "tawny eagle",
        "seagull",
        "pelican",
        "tern",
        "black-winged kite",
        "mississippi kite",
        "vulture",
        "turkey vulture",
        "griffon vulture",
        "bearded vulture",
        "new world vulture",
        "egyptian vulture",
        "lappet-faced vulture",
        "white-rumped vulture",
        "king vulture",
        "cape vulture",
        "kite",
        "falcon",
        "pigeon",
        "dove",
        "owl",
        "hummingbird",
        "penguin",
        "swallow",
        "finches",
        "sparrow",
        "toucan",
        "heron",
        "thrush",
        "bird-of-pradise",
        "woodpecker",
        "albatross",
        "ibis",
        "wren",
        "passerine",
        "crane",
        "stork",
        "bulbul",
        "swifts",
        "hornbill",
        "moa",
        "hoopoes",
        "cormorant",
        "potoo",
        "polver",
        "cuckoo",
        "sternidae",
        "lark",
        "goose",
        "grouse",
        "accipitriform (hawks, eagles, and kites)",
        "fowl",
        "flamingo",
        "guineafowl",
        "bustard",
        "terror bird",
        "kingfisher",
        "turaco",
        "sandpiper",
        "shorebird",
        "laridae",
        "waterfowl",
        "grebes",
        "auk",
        "gull",
        "bee-eater",
        "rail",
        "turkey",
        "chicken",
        "rooster"
      ],
      "parrots":    [
        "parrot",
        "cockatoo",
        "lovebird",
        "macaw",
        "new zealand parrot (Strigopidae)"
      ],
      "insects":    [
        "beetle",
        "bee",
        "wasp",
        "ant",
        "mosquito",
        "butterfly",
        "moth",
        "fly",
        "cricket",
        "horse-fly",
        "flea",
        "ladybird beetle (aka ladybug)",
        "termite",
        "cicadoidea",
        "dragonfly",
        "mantis",
        "earwig",
        "firefly (aka lightning bug)",
        "grasshopper",
        "botfly",
        "lice",
        "booklice"
      ],
      "arthropods": [
        "spider",
        "crustaocean",
        "scorpion",
        "crab",
        "tick",
        "centipede",
        "millipede",
        "shrimp"
      ],
      "reptiles":   [
        "turtle",
        "lizard",
        "dinosaur",
        "flying dinosaur",
        "chameleon",
        "crocodile",
        "gecko",
        "skink",
        "iguana",
        "lacertid",
        "gekkota",
        "hylonomus"
      ],
      "amphibians": [
        "frog",
        "toad",
        "salamander",
        "caecilian"
      ],
      "snakes":     [
        "anaconda",
        "viper",
        "python",
        "mamba",
        "cobra",
        "kingsnake",
        "colubrid snake",
        "taipan",
        "garter snake",
        "boa",
        "elapid snake",
        "coral reef snake",
        "anilius"
      ],
      "fishs":      [
        "fish",
        "shark",
        "whale",
        "trout",
        "salmon",
        "cod",
        "bass",
        "perch",
        "hake",
        "sardine",
        "sole",
        "plaice",
        "minnow",
        "billfish",
        "platy",
        "tetra",
        "pufferfish",
        "catfish",
        "flathead catfish",
        "cory catfish",
        "bristlenose catfish",
        "snakehead",
        "bowfin",
        "herring",
        "halibut",
        "tilapia",
        "common carp",
        "goldfish",
        "siamese fighting fish",
        "guppy",
        "northern pike",
        "wels catfish",
        "gilt-head bream",
        "european bass",
        "zander",
        "baramundi",
        "mahi-mahi",
        "blue tang",
        "japanese amberjack",
        "european perch",
        "muskellunge",
        "atlantic cod",
        "atlantic mackerel",
        "arapaima gigas",
        "oscar",
        "common ling",
        "european eel",
        "angler",
        "lophius piscatorius",
        "turbot",
        "tench",
        "squalius cephalus",
        "burbot",
        "iridescent shark",
        "garfish",
        "common molly",
        "common break",
        "common roach",
        "rainbow trout",
        "flathead grey mullet",
        "neon tetra",
        "green swordtail",
        "ocean sunfish",
        "pollock",
        "arctic char",
        "haddock",
        "great white shark",
        "merluccius merluccius (aka cornish salmon)",
        "candiru",
        "atlantic salmon",
        "atlantic horse mackerel",
        "common dentex",
        "southern platyfish",
        "ide",
        "bluegill",
        "brown trout",
        "pollack",
        "largemouth bass",
        "smallmouth bass",
        "algae eater",
        "barbel",
        "mahseer",
        "kokopu",
        "gudgeon",
        "darter",
        "tigerfish",
        "silver dollar",
        "barb",
        "upside-down catfish",
        "pacu",
        "cisco",
        "longperch",
        "seer",
        "headstander",
        "red seabream",
        "green spotted puffer",

        "hammerhead",
        "catshark",
        "sand shark",
        "sawshark",
        "angel shark",
        "angular roughshark",
        "carpet shark",
        "orca (aka killer whale)",
        "blue whale",
        "sperm whale",
        "humpback whale",
        "beluga whale",
        "narwhal",
        "gray whale",
        "fin whale",
        "bowhead whale",
        "north atlantic right whale",
        "north pacific right whale",
        "livyatan",
        "dolphin",
        "amazon river dolphin",
        "short-finned pilot whale",
        "bryde's whale",
        "sothern right whale",
        "sei whale",
        "false killer whale",
        "baiji",
        "common minke whale",
        "long-finned pilot whale",
        "south asian river dolphin",
        "pygmy sperm whale",
        "omura's whale",
        "northern bottlenose whale",
        "dward sperm whale",
        "la plata dolphin",
        "pygmy right whale",
        "southern bottlenose whale",
        "strap-toothed whale",
        "sowerby's beaked whale",
        "antarctic minke whale",
        "tropical bottlenose whale",
        "ginkgo-toothed beaked whale",
        "pygmy beaked whale",
        "andrew's beaked whale",
        "gray's beaked whale",
        "shepherd's beaked whale",
        "hector's beaked whale"
      ]
    },
    JSONItems   = [
      "standard",
      "dogs",
      "felidae",
      "wolfs",
      "bears",
      "rodents",
      "birds",
      "parrots",
      "insects",
      "arthropods",
      "reptiles",
      "amphibians",
      "snakes",
      "fishs"
    ];

// generate a random number
function randomNumber(n) {
  return Math.round( Math.random() * n );
}

function init() {
  ranMood     = randomNumber(moodsJSON.length);
  ranMood     = moodsJSON[ranMood];
  ranJob      = randomNumber(jobsJSON.length);
  ranJob      = jobsJSON[ranJob];
  ranJSONItem = JSONItems[randomNumber(JSONItems.length)];
  grabJSObj   = designJSONS[""+ ranJSONItem +""];
  grabItem    = grabJSObj[ randomNumber(grabJSObj.length) ];
  output      = grabItem;
  
  // detect if job starts with a vowel or not
  str = ranJob.substring(0, 1).toLowerCase();
  if (str === "a" || str === "e" || str === "i" || str === "o" || str === "u") {
    ranJob = "an " + ranJob;
  } else {
    ranJob = "a " + ranJob;
  }
  
  // generate character to draw
  character.innerHTML = ranMood + " " + output;
  scenario.innerHTML = "Category: " + ranJSONItem + "<br>Draw: " + ranMood + " " + output + "<br>Who's job is " + ranJob + "<br>&nbsp;";
  return false;
}
init();

generate.onclick = function() {
  init();
};













































