var str, ranMood, moodLink, jobLink, ranJob, ranJSONItem, grabJSObj, output, 
    moodsJSON   = [
      "accomplished",
      "admiring",
      "aggravated",
      "agitated",
      "alive",
      "alone",
      "amazed",
      "amazing",
      "ambitious",
      "amused",
      "angry",
      "annoyed",
      "annoying",
      "ashamed",
      "asleep",
      "attractive",
      "awesome",
      "awful",
      "bad",
      "balloon",
      "bashful",
      "battle damaged hero",
      "beautiful",
      "blank",
      "blessed",
      "blind",
      "blissful",
      "bored",
      "brave",
      "broken",
      "calm",
      "casual",
      "cheerful",
      "chibi",
      "chill",
      "choleric",
      "chubby",
      "clumsy",
      "cold",
      "comfortable",
      "concerned",
      "confident",
      "confused",
      "controlling",
      "cunning",
      "cool",
      "crazy",
      "creepy",
      "crippled",
      "curious",
      "cute",
      "damaged",
      "dancing",
      "deaf",
      "delighted",
      "depressed",
      "determined",
      "dirty",
      "disabled",
      "disappointed",
      "distracted",
      "down",
      "dopey",
      "drained",
      "eight-eyed",
      "eight-legged",
      "elaborate",
      "emotional",
      "energetic",
      "energized",
      "excited",
      "exhausted",
      "exhilarated",
      "excessive",
      "expressive",
      "fabulous",
      "fancy",
      "fat",
      "fearful",
      "fed up",
      "festive",
      "flirty",
      "focused",
      "frightened",
      "fresh",
      "frustrated",
      "funny",
      "furious",
      "gangly",
      "geeky",
      "gentle",
      "giddy",
      "gigantic",
      "glad",
      "gloomy",
      "glowing",
      "good",
      "goofy",
      "gorgeous",
      "grateful",
      "great",
      "greedy",
      "guilty",
      "happy",
      "hearing impared",
      "heartbroken",
      "hero",
      "heroic",
      "homeless",
      "hopeful",
      "horrible",
      "hot",
      "humorous",
      "humungous",
      "hungry",
      "hurt",
      "hyper",
      "hypnotized",
      "idyllic",
      "in love",
      "incomplete",
      "inspired",
      "intelligent",
      "irritated",
      "jealous",
      "jolly",
      "joyful",
      "laughing",
      "large",
      "lazy",
      "lighthearted",
      "lonely",
      "lost",
      "loved",
      "lovely",
      "lucky",
      "mad",
      "magic",
      "magical",
      "melancholic",
      "mesmerized",
      "messy",
      "mischievous",
      "missing",
      "motivated",
      "mysterious",
      "naked",
      "narcissistic",
      "neat",
      "nerdy",
      "nostalgic",
      "observant",
      "obsessed",
      "old",
      "ominous",
      "one-legged",
      "one-eyed",
      "optimistic",
      "overweight", 
      "overwhelmed",
      "partying",
      "pained",
      "paranoid",
      "peaceful",
      "perplexed",
      "phlegmatic",
      "pissed",
      "pissed off",
      "possessed",
      "possessive",
      "positive",
      "powerful",
      "pretty",
      "professional",
      "proud",
      "psychopath",
      "pumped calm",
      "puzzled",
      "ragged",
      "reflective",
      "refreshed",
      "relaxed",
      "romantic",
      "rough",
      "royal",
      "sad",
      "safe",
      "sanguine",
      "sarcastic",
      "satisfied",
      "savage",
      "scared",
      "scary",
      "sexy",
      "sharp",
      "shy",
      "sick",
      "silly",
      "sleepy",
      "sleeping",
      "small",
      "smart",
      "sneaky",
      "sneezy",
      "sorry",
      "special",
      "stressed",
      "strict",
      "strong",
      "stunning",
      "stupid",
      "superhero",
      "supersized",
      "surprised",
      "sweaty",
      "tall",
      "tense",
      "terrible",
      "thankful",
      "thoughtful",
      "thrilled",
      "tiny",
      "tired",
      "ugly",
      "vision impared",
      "violent",
      "war hero",
      "weird",
      "welcome",
      "well",
      "whimsical",
      "wonderful",
      "worried",
      "worse"
    ],
    jobsJSON    = [
      "secret vigilante",
      "juggler",
      "burglar",
      "criminal",
      "thug",
      "gang banger",
      "ninja",
      "knight",
      "assassin",
      "secret agent",
      "vigilante",
      "warrior",
      "soldier",
      "samurai",
      "full-time parent",
      "santa's helper",
      "bully",
      "super hero",
      "super villain",
      "living statue",
      "witch",
      "buddhist",
      
      // jobs list acquired from https://joboutlook.gov.au/A-Z
      "Aboriginal and Torres Strait Islander Education Worker",
      "Accommodation and Hospitality Manager",
      "Accountant",
      "Accounting Clerk",
      "Actor",
      "Actor, Dancer and Other Entertainer",
      "Actuary",
      "Acupuncturist",
      "Administration Manager",
      "Admissions Clerk",
      "Advertising and Marketing Professional",
      "Advertising Manager",
      "Advertising Specialist",
      "Advertising, Public Relations and Sales Manager",
      "Aerobics Instructor",
      "Aeronautical Engineer",
      "Aeroplane Pilot",
      "Aerospace Engineer",
      "Aged and Disabled Carer",
      "Agricultural and Forestry Scientist",
      "Agricultural and Horticultural Mobile Plant Operator",
      "Agricultural Consultant",
      "Agricultural Engineer",
      "Agricultural Scientist",
      "Agricultural Technician",
      "Agricultural, Forestry & Horticultural Operator",
      "Agronomist",
      "Air Traffic Controller",
      "Air Transport Professional",
      "Airconditioning and Mechanical Services Plumber",
      "Airconditioning and Refrigeration Mechanic",
      "Aircraft Baggage Handler and Airline Ground Crew",
      "Aircraft Maintenance Engineer",
      "Aircraft Maintenance Engineer (Avionics)",
      "Aircraft Maintenance Engineer (Mechanical)",
      "Aircraft Maintenance Engineer (Structures)",
      "Aircraft Refueller",
      "Alarm, Security and Surveillance Monitor",
      "Alternative Health Therapist",
      "Ambulance Officer",
      "Ambulance Officer and Paramedic",
      "Amusement Centre Manager",
      "Amusement, Fitness and Sports Centre Manager",
      "Anaesthetic Technician",
      "Anaesthetist",
      "Analyst Programmer",
      "Animal Attendant and Trainer",
      "Animator",
      "Anthropologist",
      "Antique Dealer",
      "Apiarist",
      "Apparel Cutter",
      "Applications Developer",
      "Aquaculture Farmer",
      "Aquaculture Worker",
      "Arborist",
      "Archaeologist",
      "Architect",
      "Architect (Landscape)",
      "Architectural Draftsperson",
      "Architectural, Building & Surveying Technician",
      "Archivist",
      "Archivist, Curator and Records Manager",
      "Armoured Car Escort",
      "Art Director (Film, Television or Stage)",
      "Art Teacher (Private Tuition)",
      "Artistic Director",
      "Artistic Director, Media Producer & Presenter",
      "Arts Administrator and Manager",
      "Assembly Worker",
      "Assistant in Nursing",
      "Astronomer (Physicist)",
      "Athlete",
      "Auctioneer",
      "Audiologist",
      "Audiologist and Speech Pathologist",
      "Audiometrist",
      "Audiovisual Technician (Electronic Equipment Trades Worker)",
      "Auditor, Company Secretary and Corporate Treasurer",
      "Australian Rules Footballer",
      "Author",
      "Author, and Book and Script Editor",
      "Autoglazier",
      "Automobile Driver",
      "Automotive Electrician",

      "Backhoe Operator",
      "Baker",
      "Baker and Pastrycook",
      "Bakery Assistant",
      "Baking Factory Worker",
      "Bank Manager and Branch Manager",
      "Bank Teller",
      "Bank Worker",
      "Bar Attendant",
      "Bar Attendant and Barista",
      "Bar Useful and Busser",
      "Barber",
      "Barista",
      "Barrister",
      "Beauty Therapist",
      "Bed and Breakfast Operator",
      "Beef Cattle Farm Worker",
      "Beef Cattle Farmer",
      "Beekeeper",
      "Betting Agency Counter Clerk",
      "Betting Agency Manager",
      "Betting Clerk",
      "Bicycle Mechanic",
      "Binders, Finisher and Screen Printer",
      "Biochemist",
      "Biologist",
      "Biomedical Engineer",
      "Biotechnologist",
      "Blacksmith",
      "Blasting Worker",
      "Blogger, Critic, Sports and Other Writer",
      "Blood Collector (Pathology Collector)",
      "Boarding Kennel and Cattery Operator",
      "Boat Builder and Repairer",
      "Boat Builder and Shipwright",
      "Body Artist",
      "Boiler and Engine Operator",
      "Boilermaker",
      "Boilermaker's Assistant",
      "Boner and Slicer",
      "Book and Script Editor",
      "Bookkeeper",
      "Bookmaker",
      "Bookmaker's Clerk",
      "Botanist",
      "Bouncer",
      "Branch Manager (Financial Services)",
      "Brewery Worker",
      "Bricklayer",
      "Bricklayer and Stonemason",
      "Bricklayer's Assistant",
      "Broadcast Transmitter Operator",
      "Broker (Financial)",
      "Builder's Labourer",
      "Building and Construction Manager",
      "Building and Engineering Technician",
      "Building and Plumbing Labourer",
      "Building Associate",
      "Building Certifier",
      "Building Economist",
      "Building Estimator",
      "Building Inspector",
      "Building Insulation Installer",
      "Building Manager",
      "Building Surveyor",
      "Building Technician",
      "Bulk Materials Handling Plant Operator",
      "Bulldozer Operator",
      "Bungy Jump Master",
      "Bus and Coach Driver",
      "Bus Driver",
      "Business Analyst (ICT)",
      "Business Broker",
      "Business Machine Mechanic",
      "Business Manager",
      "Business Owner",
      "Business Services Manager",
      "Butchers and Smallgoods Maker",
      "Buyer (Retail and Wool)",
      
      "Cabin Crew",
      "Cabinetmaker",
      "Cabler (Data and Telecommunications)",
      "Cafe and Restaurant Manager",
      "Cafe Worker",
      "Cake Decorator (Pastrycook)",
      "Call Centre or Contact Centre Manager",
      "Call Centre or Contact Centre Operator",
      "Call Centre or Contact Centre Team Leader",
      "Call or Contact Centre Workers",
      "Call, Contact Centre & Customer Service Manager",
      "Camera Operator (Film, Television or Video)",
      "Canvas and Leather Goods Maker",
      "Canvas Goods Fabricator",
      "Car Detailer",
      "Car Mechanic",
      "Car Park Attendant",
      "Car Parts & Accessories Fitter",
      "Car Salesperson",
      "Caravan Park and Camping Ground Manager",
      "Cardiac Technician",
      "Cardiologist",
      "Cardiothoracic Surgeon",
      "Careers Adviser",
      "Careers Counsellor",
      "Carer (Aged and Disabled)",
      "Carer (Children)",
      "Caretaker",
      "Carpenter",
      "Carpenter and Joiner",
      "Carpenter's Assistant",
      "Carpet Cleaner",
      "Carpet Layer",
      "Cartographer",
      "Cash Van Salesperson",
      "Cashier",
      "Cement and Concrete Plant Worker",
      "Cement Production Plant Operator",
      "Certifier (Building)",
      "Charter and Tour Bus Driver",
      "Chauffeur",
      "Checkout Operator",
      "Checkout Operator and Office Cashier",
      "Checkout Supervisor",
      "Cheese Maker",
      "Chef",
      "Chemical and Materials Engineer",
      "Chemical Engineer",
      "Chemical Plant Operator",
      "Chemical Plant Worker",
      "Chemical Production Machine Operator",
      "Chemical, Gas, Petroleum & Power Plant Operator",
      "Chemistry Technician",
      "Chemist",
      "Chemist, and Food and Wine Scientist",
      "Chief Executive and Managing Director",
      "Chief Financial Officer",
      "Chief Information Officer",
      "Chief Operating Officer",
      "Child and Youth Residential Care Assistant",
      "Child Care Centre Manager",
      "Child Care Worker",
      "Child Carer",
      "Chinese Medicine Practitioner",
      "Chiropractor",
      "Chiropractor and Osteopath",
      "Chocolate Packer",
      "Choreographer",
      "Cinema and Theatre Manager",
      "Cinematographer",
      "Civil Celebrant",
      "Civil Engineering Draftsperson",
      "Civil Engineering Draftsperson and Technician",
      "Civil Engineering Professional",
      "Civil Engineering Technician",
      "Civil Engineer",
      "Classified Advertising Clerk",
      "Clay Processing Factory Worker",
      "Clay Products Machine Operator",
      "Clay, Concrete, Glass & Stone Machine Operator",
      "Cleaner (Commercial)",
      "Cleaner (Domestic)",
      "Cleaner",
      "Clerical and Administrative Worker",
      "Clerical and Office Support Worker",
      "Clerk",
      "Clerk (Accounting)",
      "Clerk (Betting)",
      "Clerk (Court and Legal)",
      "Clerk (Filing and Registry)",
      "Clerk (Human Resource)",
      "Clerk (Inquiry)",
      "Clerk (Insurance, Money Market and Statistical)",
      "Clerk (Payroll)",
      "Clerk (Purchasing and Supply Logistics)",
      "Clerk (Transport and Despatch)",
      "Clerk of Court",
      "Climatologist (Meteorologist)",
      "Clinical Coder",
      "Clinical Haematologist",
      "Clinical Psychologist",
      "Clothing Patternmaker",
      "Clothing Trades Worker",
      "Club Manager",
      "Coache (Sports)",
      "Commercial Cleaner",
      "Commercial Housekeeper",
      "Commissioned Defence Force Officer",
      "Commissioned Fire Officer",
      "Commissioned Officer (Management)",
      "Commissioned Police Officer",
      "Commodities Trader",
      "Communications Manager",
      "Communications Operator",
      "Communications Technician",
      "Communications Trades Worker",
      "Community Arts Worker",
      "Community Health Worker",
      "Community Worker",
      "Company Secretary",
      "Complementary Health Therapist",
      "Composer",
      "Computer Network and Systems Engineer",
      "Computer Network Professional",
      "Concierges (Hotel Service Manager)",
      "Concrete Batching Plant Operator",
      "Concrete Products Machine Operator",
      "Concrete Pump Operator",
      "Concreter",
      "Conductor (Transport)",
      "Confectionery Maker",
      "Conference and Event Organiser",
      "Conservation Officer",
      "Conservator",
      "Construction Estimator",
      "Construction Manager",
      "Construction Plant Operator",
      "Construction Project Manager",
      "Construction Rigger",
      "Construction Worker",
      "Container Filler",
      "Contract Administrator",
      "Contract, Program and Project Administrator",
      "Conveyancer",
      "Conveyancer and Legal Executive",
      "Cook",
      "Cook (Fast Food)",
      "Copywriter",
      "Coremaker",
      "Corporate General Manager",
      "Corporate Services Manager",
      "Corporate Treasurer",
      "Correctional Officer",
      "Cost Clerk",
      "Costume Designer (Fashion Designer)",
      "Cotton Grower",
      "Councillor",
      "Counselling Psychologist",
      "Counsellor",
      "Courier",
      "Courier and Postal Deliverer",
      "Court and Legal Clerk",
      "Court Bailiff and Sheriff",
      "Court Clerk",
      "Court Orderly",
      "Crane Chaser",
      "Crane, Hoist and Lift Operator",
      "Creative Director (Advertising)",
      "Credit and Loans Officer",
      "Criminologist",
      "Crop Farm Worker",
      "Crop Farmer",
      "Crossing Supervisor",
      "Croupier",
      "Crowd Controller",
      "Curator",
      "Customer Service Manager",
      "Customs Broker",
      "Customs Officer",
      
      "Dairy Cattle Farm Worker",
      "Dairy Cattle Farmer",
      "Dairy Products Maker",
      "Dance Teacher (Private Tuition)",
      "Dancer and Choreographer",
      "Data Entry Operator",
      "Database & Systems Administrator & ICT Security",
      "Database Administrator",
      "Dealer (Financial)",
      "Debt Collector",
      "Deck and Fishing Hand",
      "Deck Hand",
      "Deck Officer",
      "Deer Farmer",
      "Defence Force Member",
      "Defence Force Senior Officer",
      "Delivery Driver",
      "Demonstrator (Sales)",
      "Dental Assistant",
      "Dental Hygienist",
      "Dental Hygienist, Technician and Therapist",
      "Dental Practitioner",
      "Dental Prosthetist",
      "Dental Specialist (including Orthodontist)",
      "Dental Technician",
      "Dental Therapist",
      "Dentist",
      "Dermatologist",
      "Designer (Fashion, Industrial and Jewellery)",
      "Designer (Graphic and Web)",
      "Designer (Interior)",
      "Despatch Clerk",
      "Despatching and Receiving Clerk",
      "Detailer",
      "Detective",
      "Developer Programmer",
      "Development Manager",
      "Diagnostic and Interventional Radiologist",
      "Die Setter",
      "Diesel Motor Mechanic",
      "Dietitian",
      "Director (Child Care)",
      "Director (Film, Television, Radio or Stage)",
      "Director of Nursing",
      "Disabilities Services Officer",
      "Disabled Carer",
      "Disk Jockey (Nightclub)",
      "Disk Jockey (Radio)",
      "Dispensary Technician",
      "Diver",
      "Diversional Therapist",
      "Doctor",
      "Dog and Horse Racing Official",
      "Dog Handler and Trainer",
      "Dogmen (Crane Chaser)",
      "Domestic Cleaner",
      "Domestic Housekeeper",
      "Doorperson and Luggage Porter",
      "Door-to-door Salesperson",
      "Draftsperson (Civil Engineering)",
      "Draftsperson (Electrical Engineering)",
      "Draftsperson (Electronic Engineering)",
      "Draftsperson (Mechanical Engineering)",
      "Drainage, Sewerage and Stormwater Labourer",
      "Drainer",
      "Drama Teacher (Private Tuition)",
      "Dressmaker and Tailor",
      "Driller",
      "Driller's Assistant",
      "Driller, Miner and Shot Firer",
      "Driver (Automobile)",
      "Driver (Bus and Coach)",
      "Driver (Delivery)",
      "Driver (Forklift)",
      "Driver (Train and Tram)",
      "Driver (Truck)",
      "Driveway Attendant",
      "Driving Instructor",
      "Drug and Alcohol Counsellor",
      "Drycleaner",
      
      "Ear, Nose and Throat Specialist",
      "Early Childhood (Pre-primary School) Teacher",
      "Earth Science Technician",
      "Earthmoving Labourer",
      "Earthmoving Plant Operator",
      "Ecologist (Environmental Scientists)",
      "Economist",
      "Editor (Book and Script)",
      "Education Adviser",
      "Education Adviser and Reviewer",
      "Education Aide",
      "Education Manager",
      "Education Reviewer",
      "Educational Psychologist",
      "Electorate Officer",
      "Electrical and Telecommunications Trades Assistant",
      "Electrical Distribution Trades Worker",
      "Electrical Engineering Draftsperson",
      "Electrical Engineering Draftsperson, Technician",
      "Electrical Engineering Technician",
      "Electrical Engineer",
      "Electrical Linesworker",
      "Electrician",
      "Electrician (Special Class)",
      "Electronic Engineering Draftsperson",
      "Electronic Engineering Draftsperson, Technician",
      "Electronic Engineering Technician",
      "Electronic Equipment Trades Worker",
      "Electronic Instrument Trades Worker",
      "Electronics Engineer",
      "Electronics Trades Worker",
      "Electroplater",
      "Emergency Medicine Specialist",
      "Emergency Service Worker",
      "Employment Consultant",
      "Endocrinologist",
      "Engineering Manager",
      "Engineering Patternmaker",
      "Engineering Production Worker",
      "Engineering Professional",
      "Engineering Technologist",
      "Engineer",
      "Engineer (Chemical and Material)",
      "Engineer (Civil)",
      "Engineer (Electrical)",
      "Engineer (Electronics)",
      "Engineer (Industrial, Mechanical & Production)",
      "Engineer (Mining)",
      "Engineer (Telecommunications)",
      "English as a Second Language Teacher",
      "Engraver",
      "Enrolled and Mothercraft Nurse",
      "Enrolled Nurse",
      "Entertainer and Variety Artist",
      "Entertainment Centre Manager",
      "Environmental Consultant",
      "Environmental Engineer",
      "Environmental Health Officer",
      "Environmental Manager",
      "Environmental Research Scientist",
      "Environmental Scientist",
      "Equipment Hire Manager",
      "Event Manager",
      "Event Organiser",
      "Examination Supervisor",
      "Excavator Operator",
      "Exercise Physiologist",
      "Exhaust and Muffler Repairer",
      "Exporter",
      "External Auditor",
      "Eye Specialist",
      "Eye Surgeon",
      
      "Fabric and Textile Factory Worker",
      "Facilities Administrator",
      "Facilities Manager",
      "Factory Process Worker",
      "Factory Worker (Food and Drink)",
      "Factory Worker (Plastics and Rubber)",
      "Faculty Head",
      "Family and Marriage Counsellor",
      "Family Day Care Worker",
      "Family Support Worker",
      "Farm Worker (Crops)",
      "Farm Worker (Livestock)",
      "Farm Worker (Mixed Crop and Livestock)",
      "Farm, Forestry and Garden Worker",
      "Farmer (Aquaculture)",
      "Farmer (Crops)",
      "Farmer (Livestock)",
      "Farmer (Mixed Crop and Livestock)",
      "Farrier",
      "Fashion Designer",
      "Fashion, Industrial and Jewellery Designer",
      "Fast Food Cook",
      "Fencer",
      "Fettler",
      "Fibreglass Laminator",
      "Fibrous Plasterer",
      "Filing and Registry Clerk",
      "Film and Video Editor",
      "Film Producer",
      "Film, Television, Radio and Stage Director",
      "Finance Broker",
      "Finance Manager",
      "Financial Broker",
      "Financial Controller",
      "Financial Dealer",
      "Financial Institution Branch Manager",
      "Financial Investment Adviser",
      "Financial Investment Adviser and Manager",
      "Financial Investment Manager",
      "Financial Market Dealer",
      "Fire and Emergency Worker",
      "Fire Fighter",
      "Fire Protection Equipment Technician",
      "First Aid Trainer",
      "Fisheries Officer",
      "Fishing Guide",
      "Fishing Hand",
      "Fitness Centre Manager",
      "Fitness Instructor",
      "Fitter",
      "Fitter and Turner",
      "Fitter's Assistant",
      "Fitter-Welder",
      "Fleet Manager",
      "Flight Attendant",
      "Floor Finisher",
      "Floor Tiler",
      "Florist",
      "Flower Grower",
      "Flying Instructor",
      "Food and Beverage Attendant",
      "Food and Beverage Manager",
      "Food and Drink Factory Worker",
      "Food and Wine Scientist",
      "Food Scientist",
      "Food Technologist",
      "Food Trades Assistant",
      "Footballer (Soccer, Rugby and AFL)",
      "Footwear Factory Worker",
      "Footwear Production Machine Operator",
      "Forensic Psychologist (Clinical Psychologist)",
      "Forest Manager",
      "Forester",
      "Forestry and Logging Worker",
      "Forestry Worker",
      "Forklift Driver",
      "Freight and Furniture Handler",
      "Freight Handler (Rail or Road)",
      "Fruit and Nut Farm Worker",
      "Fruit and Nut Grower",
      "Fruit and Nut Picker",
      "Fruit and Vegetable Factory Worker",
      "Fruit and Vegetable Packer",
      "Funeral Director",
      "Funeral Worker",
      "Furniture Finisher",
      "Furniture Removalist Driver",
      "Furniture Removalist's Assistant",
      "Futures Trader",
      
      "Gallery and Museum Curator",
      "Gallery and Museum Guide",
      "Gallery and Museum Technician",
      "Gallery, Library and Museum Technician",
      "Gallery, Museum and Tour Guide",
      "Game and Multimedia Developer",
      "Game Developer (Electronic)",
      "Gaming Worker",
      "Garbage Collector",
      "Garden and Nursery Labourer",
      "Garden Labourer",
      "Gardener",
      "Gas and Petroleum Operator",
      "Gas Plant Operator",
      "Gasfitter",
      "Gastroenterologist",
      "General Clerk",
      "General Manager",
      "General Practitioner",
      "General Practitioner and Resident Medical Officer",
      "Genetic Counsellor",
      "Geographer",
      "Geologist",
      "Geologist, Geophysicist and Hydrogeologist",
      "Geophysicist",
      "Geotechnical Engineer",
      "Glass Maker",
      "Glass Processing Worker",
      "Glass Production Machine Operator",
      "Glazier",
      "Goat Farmer",
      "Golfer",
      "Grader Operator",
      "Grain Mill Worker",
      "Grain, Oilseed and Pasture Farm Worker",
      "Grain, Oilseed and Pasture Grower",
      "Grape Grower",
      "Graphic and Web Designer, and Illustrator",
      "Graphic Designer",
      "Graphic Pre-press Trades Worker",
      "Greenkeeper",
      "Group Leader (Child Care)",
      "Guide (Outdoor Adventure)",
      "Gunsmith",
      "Gymnastics Coach and Instructor",
      "Gynaecologist and Obstetrician",
      
      "Hair and Beauty Salon Assistant",
      "Hair and Beauty Salon Manager",
      "Hairdresser",
      "Handyperson",
      "Hardware Technician",
      "Health and Welfare Services Manager",
      "Health Diagnostic and Promotion Professional",
      "Health Educator",
      "Health Information Manager",
      "Health Practice Manager",
      "Health Professional",
      "Health Promotion Officer",
      "Helicopter Pilot",
      "Herbalist (Western)",
      "Hide and Skin Processing Machine Operator",
      "Hide and Skin Processing Worker",
      "High School Teacher (Secondary School)",
      "Historian",
      "Home Improvement Installer",
      "Homoeopath",
      "Horse Breeder",
      "Horse Riding Coach and Instructor",
      "Horse Trainer",
      "Horticultural Nursery Assistant",
      "Hospital Orderlies",
      "Hospital Pharmacists",
      "Hospital Ward Clerks",
      "Hospitality Worker",
      "Hospitality, Retail and Service Manager",
      "Hostel Parent",
      "Hotel and Motel Manager",
      "Hotel and Motel Receptionist",
      "Hotel Service Manager",
      "Housekeeper",
      "Human Resource Adviser",
      "Human Resource Clerk",
      "Human Resource Manager",
      "Human Resource Professional",
      "Hunter-Trapper",
      "Hunting Guide",
      "Hydrogeologist",
      "Hydrographer",
      "Hydrologist",
      
      "Information and Communications Technology (ICT) Account Manager",
      "Information and Communications Technology (ICT) Business Analyst",
      "Information and Communications Technology (ICT) Business and Systems Analyst",
      "Information and Communications Technology (ICT) Business Development Manager",
      "Information and Communications Technology (ICT) Customer Support Officer",
      "Information and Communications Technology (ICT) Manager",
      "Information and Communications Technology (ICT) Project Manager",
      "Information and Communications Technology (ICT) Quality Assurance Engineer",
      "Information and Communications Technology (ICT) Sales Assistant",
      "Information and Communications Technology (ICT) Sales Professional",
      "Information and Communications Technology (ICT) Sales Representative",
      "Information and Communications Technology (ICT) Security Specialist",
      "Information and Communications Technology (ICT) Support and Test Engineer",
      "Information and Communications Technology (ICT) Support Engineer",
      "Information and Communications Technology (ICT) Support Technician",
      "Information and Communications Technology (ICT) Systems Test Engineer",
      "Information and Communications Technology (ICT) Trainer",
      "Illustrator",
      "Immigration Officer",
      "Importer and Exporter",
      "Importer, Exporter and Wholesaler",
      "Import-Export Clerk",
      "Indigenous Health Worker",
      "Industrial Designer",
      "Industrial Engineer",
      "Industrial Pharmacist",
      "Industrial Psychologist",
      "Industrial Spraypainter",
      "Industrial, Mechanical and Production Engineer",
      "Information and Organisation Professional",
      "Information Officer",
      "Inspectors and Regulatory Officer",
      "Insulation and Home Improvement Installer",
      "Insurance Agent",
      "Insurance Broker",
      "Insurance Consultant",
      "Insurance Investigator",
      "Insurance Investigator, Loss Adjuster and Risk Surveyor",
      "Insurance Loss Adjuster",
      "Insurance Risk Surveyor",
      "Insurance, Money Market and Statistical Clerk",
      "Integration Aide",
      "Intellectual Property Lawyer",
      "Intelligence and Policy Analyst",
      "Intelligence Officer",
      "Intensive Care Ambulance Paramedic",
      "Intensive Care Specialist",
      "Interior Decorator",
      "Interior Designer",
      "Internal Auditor",
      "Interpreter",
      "Interviewer (Surveys)",
      "Investment Adviser",
      "Ironer and Presser",
      
      "Janitor",
      "Jeweller",
      "Jewellery Designer",
      "Jockey",
      "Joiner",
      "Journalist and Other Writer",
      "Judge",
      "Judicial and Other Legal Professional",
      
      "Kennel Hand",
      "Keyboard Operator",
      "Kindergarten Teacher (Early Childhood)",
      "Kitchenhand",
      "Knitting Machine Operator",
      
      "Laboratory Manager",
      "Labourer",
      "Labourer (Building and Plumbing)",
      "Labourer (Garden and Nursery)",
      "Labourer (Paving and Surfacing)",
      "Labourer (Railway)",
      "Lagger",
      "Land Economist",
      "Land Economist and Valuer",
      "Landscape Architect",
      "Landscape Gardener",
      "Laundry Worker",
      "Law Clerk",
      "Lawn Mower",
      "Leaflet and Newspaper Deliverer",
      "Leather Goods Maker",
      "Lecturer and Tutor (University)",
      "Legal Clerk",
      "Legal Executive",
      "Legal Secretary",
      "Legislator",
      "Liaison Officer",
      "Librarian",
      "Library Assistant",
      "Library Technician",
      "Licensed Club Manager",
      "Life Science Technician",
      "Life Scientist",
      "Lifeguard",
      "Lift Mechanic",
      "Light Technician",
      "Linemarker",
      "Linesmen",
      "Linesperson (Electrical)",
      "Linesperson (Telecommunications)",
      "Linguist",
      "Livestock Farm Worker",
      "Livestock Farmer",
      "Loader Operator",
      "Loans Officer",
      "Local Government Legislator",
      "Locksmith",
      "Logging Assistant",
      "Logging Plant Operator",
      "Logistics Clerk (Production Clerk)",
      "Logistics Manager",
      "Loss Adjuster",
      "Lotteries Agent",
      
      "Machine Operator",
      "Machine Operator (Clay, Concrete, Glass & Stone)",
      "Machine Operator (Paper and Wood Processing)",
      "Machine Operator (Plastics and Rubber Production)",
      "Machine Operator (Textile & Footwear Production)",
      "Machine Shorthand Reporter",
      "Machinist (Metal)",
      "Machinist (Sewing)",
      "Machinist (Wood)",
      "Magistrate",
      "Mail Clerk",
      "Mail Sorter",
      "Maintenance Fitter (Fitters)",
      "Maintenance Planner",
      "Make Up Artist",
      "Management Accountant",
      "Management and Organisation Analyst",
      "Management Consultant",
      "Manager (Advertising and Sales)",
      "Manager (Amusement, Fitness and Sports Centre)",
      "Manager (Cafe and Restaurant)",
      "Manager (Caravan Park and Camping Ground)",
      "Manager (Child Care Centre)",
      "Manager (Construction)",
      "Manager (Corporate Services)",
      "Manager (Engineering)",
      "Manager (Finance)",
      "Manager (Health and Welfare Services)",
      "Manager (Hotel and Motel)",
      "Manager (Human Resources)",
      "Manager (ICT)",
      "Manager (Licenced Club)",
      "Manager (Non-school Education)",
      "Manager (Policy and Planning)",
      "Manager (Production)",
      "Manager (Research and Development)",
      "Manager (Retail)",
      "Manager (Supply and Distribution)",
      "Manager (Transport Services)",
      "Managing Director",
      "Manufacturer",
      "Manufacturing Production Manager",
      "Marine Biologist",
      "Marine Engineer",
      "Marine Surveyor",
      "Marine Transport Professional",
      "Market Research Analyst",
      "Marketing Manager",
      "Marketing Specialist",
      "Massage Therapist",
      "Master Fisher",
      "Materials Engineer",
      "Materials Recycler",
      "Mathematician",
      "Meat Boners and Slicer",
      "Meat Boners and Slicer, and Slaughterer",
      "Meat Inspector",
      "Meat Packer",
      "Meat Process Worker",
      "Meat, Poultry and Seafood Process Worker",
      "Mechanical Engineering Draftsperson",
      "Mechanical Engineering Draftsperson, Technician",
      "Mechanical Engineering Technician",
      "Mechanical Engineer",
      "Mechanical Fitter (Fitters)",
      "Mechanic's Assistant",
      "Mechatronics Engineer (Engineering Professional)",
      "Media Equipment Operator",
      "Media Producer",
      "Medical Administrator",
      "Medical Diagnostic Radiographer",
      "Medical Imaging Professional",
      "Medical Imaging Technologist",
      "Medical Laboratory Scientist",
      "Medical Laboratory Technician",
      "Medical Oncologist",
      "Medical Practitioner",
      "Medical Radiation Therapist",
      "Medical Receptionist",
      "Medical Records Administrator",
      "Medical Technician",
      "Member of Parliament",
      "Merchandiser",
      "Metal Casting Trades Worker",
      "Metal Casting, Forging & Finishing Trade",
      "Metal Engineering Process Worker",
      "Metal Fabricator",
      "Metal Fitter and Machinist",
      "Metal Machinist (First Class)",
      "Metal Polisher",
      "Metallurgical and Materials Technician",
      "Metallurgist",
      "Meteorologist",
      "Meter Reader",
      "Microbiologist",
      "Middle School Teacher",
      "Midwive",
      "Migration Agent",
      "Milliner",
      "Mine Deputy",
      "Mine Manager",
      "Miner",
      "Mining Engineer (excluding Petroleum)",
      "Mining Engineers",
      "Mining Support Workers",
      "Minister of Religion",
      "Mixed Crop and Livestock Farm Worker",
      "Mixed Crop and Livestock Farmer",
      "Mixed Crop Farmer",
      "Mixed Livestock Farm Worker",
      "Mixed Livestock Farmer",
      "Mobile Plant Operator",
      "Model",
      "Model and Sales Demonstrator",
      "Money Market Clerk",
      "Mortgage Broker",
      "Mortician",
      "Motel Manager",
      "Mothercraft Nurse",
      "Motion Picture Projectionist",
      "Motor Mechanic",
      "Motor Vehicle and Caravan Salesperson",
      "Motor Vehicle and Vehicle Parts Salesperson",
      "Motor Vehicle Licence Examiner",
      "Motor Vehicle Parts and Accessories Fitter",
      "Motor Vehicle Parts Interpreter",
      "Motorcycle Mechanic",
      "Mountain and Glacier Guide",
      "Multimedia Designer",
      "Multimedia Developer",
      "Multimedia Specialist",
      "Multimedia Specialist and Web Developer",
      "Mushroom Picker",
      "Music Director",
      "Music Professional",
      "Music Teacher (Private Tuition)",
      "Music, Dance, Drama, Play, Hypnotic, and Related Therapist",
      "Musical Instrument Maker and Repairer",
      "Musician",
      "Mystery Shopper",
      
      "Nail Technician (Beauty Therapist)",
      "Nanny",
      "Natural and Physical Science Professional",
      "Natural Remedy Consultant",
      "Naturopath",
      "Naval Architect",
      "Network Administrator",
      "Network Analyst",
      "Neurologist",
      "Neuropsychologist (Clinical Psychologist)",
      "Neurosurgeon",
      "Newspaper and Periodical Editor",
      "Night Filler",
      "Noxious Weeds and Pest Inspector",
      "Nuclear Medicine Technologist",
      "Nurse Educator",
      "Nurse Educator and Researcher",
      "Nurse Manager",
      "Nurse Practitioner",
      "Nurse Researcher",
      "Nursery Hand (Horticulture)",
      "Nurseryperson",
      "Nurse (Dental)",
      "Nurse (Enrolled)",
      "Nurse (Registered)",
      "Nurse (Veterinary)",
      "Nursing Clinical Director",
      "Nursing Support and Personal Care Worker",
      "Nursing Support Worker",
      "Nutrition Professional",
      "Nutritionist",
      
      "Obstetrician and Gynaecologist",
      "Occupational & Environmental Health Professional",
      "Occupational Health and Safety Adviser",
      "Occupational Psychologist",
      "Occupational Therapist",
      "Oenologist",
      "Office Equipment Technician",
      "Office Manager",
      "Oher Financial Dealer",
      "Oncologist (Medical)",
      "Oncologist (Radiation)",
      "Operating Room Nurse",
      "Operating Theatre Technician",
      "Operator (Switchboard)",
      "Ophthalmologist",
      "Optical Dispenser",
      "Optical Mechanic",
      "Optometrist",
      "Optometrist and Orthoptist",
      "Oral Health Therapist (Dental Therapists)",
      "Order Clerk",
      "Orderly (Hospital)",
      "Organisation and Methods Analyst",
      "Organisational Psychologist",
      "Orthopaedic Surgeon",
      "Orthoptist",
      "Orthotist and Prosthetist",
      "Osteopath",
      "Otorhinolaryngologist",
      "Out of School Hours Care Worker",
      "Outdoor Adventure Guide",
      "Outdoor Adventure Instructor",

      "Packer",
      "Paediatric Surgeon",
      "Paediatrician",
      "Painter (Visual Arts)",
      "Painting Trades Worker",
      "Panelbeater",
      "Paper and Pulp Mill Operator",
      "Paper and Pulp Mill Worker",
      "Paper and Wood Processing Machine Operator",
      "Paper Products Machine Operator",
      "Paramedic (Ambulance)",
      "Park Ranger",
      "Parking Inspector",
      "Parole and Probation Officer",
      "Passenger Coach Driver",
      "Pastrycook",
      "Pastrycook's Assistant",
      "Patent Attorney (Intellectual Property Laywer)",
      "Patents Examiner",
      "Pathologist",
      "Pathology Collector",
      "Patient Services Assistant",
      "Patternmaker (Clothing)",
      "Patternmaker (Engineering)",
      "Paving and Surfacing Labourer",
      "Paving Plant Operator",
      "Payroll Clerk",
      "Payroll Officer",
      "Performing Arts Technician",
      "Personal Assistant",
      "Personal Care Assistant",
      "Personal Care Consultant",
      "Personal Care Worker",
      "Personal Service Worker",
      "Personal Trainer",
      "Personnel Manager",
      "Personnel Officer",
      "Pest Controller",
      "Pet Groomer",
      "Petroleum Engineer",
      "Petroleum Plant Operator",
      "Pharmacist",
      "Pharmacy Sales Assistant",
      "Pharmacy Technician",
      "Phlebotomist (Pathology Collectors)",
      "Photographer",
      "Photographer's Assistant",
      "Photographic Developer and Printer",
      "Physical Therapist",
      "Physician",
      "Physicist",
      "Physiotherapist",
      "Piano Tuner",
      "Picture Framer",
      "Pig Farmer",
      "Pilot (Air Transport)",
      "Planner (Urban and Regional)",
      "Plant Mechanic (Fitters)",
      "Plant Operator",
      "Plant Operator (Agricultural, Forestry & Horticul",
      "Plant Operator (Earthmoving)",
      "Plant Operator (Stationary)",
      "Plasterer",
      "Plastic and Reconstructive Surgeon",
      "Plastic Cablemaking Machine Operator",
      "Plastic Compounding and Reclamation Machine Operator",
      "Plastic Surgeon",
      "Plastics and Rubber Factory Worker",
      "Plastics and Rubber Production Machine Operator",
      "Plastics Fabricator and Welder",
      "Plastics Factory Worker",
      "Plastics Production Machine Operator",
      "Plastics Technician",
      "Plumber",
      "Plumber's Assistant",
      "Plumbing Inspector",
      "Podiatrist",
      "Police",
      "Police Officer",
      "Policy Adviser",
      "Policy Analyst",
      "Policy and Planning Manager",
      "Political Scientist",
      "Porter",
      "Post Office Manager",
      "Postal Delivery Officer",
      "Postal Sorting Officer",
      "Potters and Ceramic Artist",
      "Poultry Farm Worker",
      "Poultry Farmer",
      "Poultry Process Worker",
      "Powder Monkey",
      "Power Generation Plant Operator",
      "Practice Manager",
      "Precision Instrument Maker and Repairer",
      "Precision Metal Trades Worker",
      "Pre-press Trades Worker",
      "Preschool Aide",
      "Preschool Teacher (Early Childhood)",
      "Presenter",
      "Pressure Welder",
      "Primary Health Organisation Manager",
      "Primary Products Inspector",
      "Primary School Teacher",
      "Principal (School)",
      "Print Finisher",
      "Print Journalist",
      "Printer",
      "Printer's Assistant",
      "Printing Assistant and Table Worker",
      "Printing Machinist",
      "Printing Table Worker",
      "Prison Officer",
      "Private Investigator",
      "Private Tutor and Teacher",
      "Probation Officer",
      "Process Worker",
      "Process Worker (Meat, Poultry and Seafood)",
      "Process Worker (Metal Engineering)",
      "Process Worker (Timber and Wood)",
      "Procurement Manager",
      "Procurement Officer",
      "Producer (Media)",
      "Product Assembler",
      "Product Designer (Industrial)",
      "Product Examiner",
      "Product Grader",
      "Product Quality Controller",
      "Product Tester",
      "Production and Plant Engineer",
      "Production Assistant (Film, Television, Radio or Stage)",
      "Production Clerk",
      "Production Manager",
      "Production Manager (Forestry)",
      "Production Manager (Mining)",
      "Production Recording Clerk",
      "Production Systems Worker (Engineering)",
      "Program Administrator",
      "Program and Project Administrator",
      "Program Director (Television or Radio)",
      "Programmer",
      "Project Administrator",
      "Project Builder",
      "Project Coordinator",
      "Proof Reader",
      "Property Manager",
      "Property Valuer",
      "Prosthetist or Orthotist",
      "Psychiatric Nurse",
      "Psychiatrist",
      "Psychologist and Psychotherapist",
      "Psychotherapist",
      "Public Relations Manager",
      "Public Relations Professional",
      "Purchasing and Supply Logistics Clerk",
      "Purchasing Officer",
      
      "Quality Assurance Assessor",
      "Quality Assurance Manager",
      "Quality Control Assessor",
      "Quantity Surveyor",
      "Quarantine Officer",
      
      "Radiation Oncologist",
      "Radiation Therapist (Medical)",
      "Radiator Repairer",
      "Radio Despatcher",
      "Radio Journalist",
      "Radio Presenter",
      "Radiocommunications Technician",
      "Radiographer",
      "Railway Signal Operator",
      "Railway Station Manager",
      "Railway Track Plant Operator",
      "Railway Track Worker",
      "Railways Assistant",
      "Ranger",
      "Real Estate Agency Principal",
      "Real Estate Agent",
      "Real Estate Representative",
      "Real Estate Sales Agent",
      "Receptionist",
      "Records Manager",
      "Recreation Officer",
      "Recreational Therapist",
      "Recruitment Consultant",
      "Recycling and Rubbish Collector",
      "Recycling Worker",
      "Referee (Sports)",
      "Refrigeration Mechanic",
      "Refuge Worker",
      "Regional Education Manager",
      "Registered Nurse",
      "Registered Nurse (Aged Care)",
      "Registered Nurse (Child and Family Health)",
      "Registered Nurse (Community Health)",
      "Registered Nurse (Critical Care and Emergency)",
      "Registered Nurse (Developmental Disability)",
      "Registered Nurse (Disability and Rehabilitation)",
      "Registered Nurse (Medical Practice)",
      "Registered Nurse (Medical)",
      "Registered Nurse (Mental Health)",
      "Registered Nurse (Paediatrics)",
      "Registered Nurse (Perioperative)",
      "Registered Nurse (Surgical)",
      "Regulatory Officer",
      "Rehabilitation Counsellor",
      "Reinforced Plastic and Composite Production Worker",
      "Religious Assistant",
      "Renal Medicine Specialist",
      "Rental Salesperson",
      "Research and Development Manager",
      "Resident Medical Officer",
      "Residential Care Officer",
      "Respiratory Medicine Physician",
      "Restaurant Manager",
      "Retail and Wool Buyer",
      "Retail Assistant",
      "Retail Buyer",
      "Retail Loss Prevention Officer",
      "Retail Manager",
      "Retail Pharmacist",
      "Retail Supervisor",
      "Retirement Village Manager",
      "Rheumatologist",
      "Rigger (Construction)",
      "Road Roller Operator",
      "Road Traffic Controller",
      "Roof Plumber",
      "Roof Tiler",
      "Rubber Factory Worker",
      "Rubber Production Machine Operator",
      "Rugby League Footballer",
      "Rugby Union Footballer",

      "Safety Inspector",
      "Sail Maker",
      "Sales Agent (Real Estate)",
      "Sales and Marketing Manager",
      "Sales Assistant",
      "Sales Assistant (ICT)",
      "Sales Assistant (Pharmacy)",
      "Sales Demonstrator",
      "Sales Manager",
      "Sales Professional (ICT)",
      "Sales Representative",
      "Sales Representative (Building and Plumbing Supplies)",
      "Sales Representative (Business Services)",
      "Sales Representative (Industrial Products)",
      "Sales Representative (Medical and Pharmaceutical Products)",
      "Sales Representative (Motor Vehicle Parts and Accessories)",
      "Sales Representative (Personal and Household Goods)",
      "Sales Representative (Technical)",
      "Salesperson (Motor Vehicle and Vehicle Parts)",
      "Salesperson (Tickets)",
      "Sand Blaster",
      "Saw Doctor",
      "Sawmill and Timber Yard Worker",
      "Sawmilling Operator",
      "Scaffolder",
      "School Cleaner (Commercial Cleaners)",
      "School Counsellor",
      "School Laboratory Technician",
      "School Principal",
      "Science Technician",
      "Screen Printer",
      "Scuba, Snorkelling and Dive instructor",
      "Sculptor",
      "Seafood Packer",
      "Seafood Process Worker",
      "Secondary School Teacher",
      "Secretary",
      "Security Consultant",
      "Security Officer",
      "Security Officer and Guard",
      "Security Specialist (ICT)",
      "Security Technician (Electronic Equipment Trades Workers)",
      "Senior Non-Commissioned Defence Force Officer",
      "Service Station Attendant",
      "Sewing Machinist",
      "Shearer",
      "Shearing Shed Hand",
      "Sheep Farm Worker",
      "Sheep Farmer",
      "Sheetmetal Trades Worker",
      "Shelf Filler",
      "Ship's Captain",
      "Ship's Engineer",
      "Ship's Master",
      "Ship's Officer",
      "Shipwright",
      "Shoemaker",
      "Shop Manager",
      "Shopfitter (Carpenter and Joiner)",
      "Short Order Cook",
      "Shot Firer",
      "Sign Erector",
      "Signwriter",
      "Singer",
      "Slaughterer",
      "Small Engine Mechanic",
      "Small Offset Printer",
      "Smallgoods Maker",
      "Snowsport Instructor",
      "Soccer Players (Footballer)",
      "Social Professional",
      "Social Security Assessor",
      "Social Worker",
      "Sociologist",
      "Software and Applications Programmer",
      "Software Developer",
      "Software Engineer",
      "Software Tester",
      "Soil Scientist",
      "Solicitor",
      "Solid Plasterer",
      "Sonographer",
      "Sound Technician",
      "Sous Chef",
      "Spare Parts Interpreter",
      "Special Care Worker",
      "Special Education Teacher",
      "Special Needs Teacher",
      "Specialist Manager",
      "Specialist Physician",
      "Specimen Collector",
      "Speech Pathologist",
      "Speech Therapist",
      "Sport Psychologist",
      "Sports Administrator",
      "Sports Centre Manager",
      "Sports Coach, Instructor and Official",
      "Sports Development Officer",
      "Sports Physiotherapist",
      "Sports Umpire",
      "Sportsperson",
      "Spraypainter (Industrial)",
      "Spraypainter (Vehicle)",
      "Stablehand",
      "Stage Manager",
      "Stationary Plant Operator",
      "Statistical Clerk",
      "Statistician",
      "Steel Fixer",
      "Sterilisation Technician",
      "Stevedore",
      "Stock and Station Agent",
      "Stock Clerk",
      "Stockbroker",
      "Stone Processing Machine Operator",
      "Stonemason",
      "Store Detective",
      "Storeperson",
      "Street Vendor",
      "Street Vendor and Related Salesperson",
      "Streetsweeper Operator",
      "Structural Engineer",
      "Structural Steel and Welding Trades Worker",
      "Structural Steel Construction Worker",
      "Structural Steel Erector",
      "Student Counsellor",
      "Sugar Cane Grower",
      "Sugar Mill Worker",
      "Supervisor (Retail)",
      "Supply and Distribution Manager",
      "Supply Chain Manager",
      "Supply, Distribution and Procurement Manager",
      "Surgeon",
      "Survey Interviewer",
      "Surveying and Spatial Science Technician",
      "Surveyor",
      "Surveyor and Spatial Scientist",
      "Surveyor's Assistant",
      "Swimming Coach and Instructor",
      "Switchboard Operator",
      "Systems Administrator",
      "Systems Analyst",
      
      "TAFE Teacher",
      "Tailor",
      "Tanker Driver",
      "Tattoo Artist (Body Artists)",
      "Taxation Accountant",
      "Taxation Inspector",
      "Taxi Driver",
      "Teacher (Early Childhood)",
      "Teacher (Middle School)",
      "Teacher (Primary School)",
      "Teacher (Private)",
      "Teacher (Secondary School)",
      "Teacher (Special Education)",
      "Teacher (Vocational Education)",
      "Teachers' Aides",
      "Teacher of English to Speakers of Other Languages",
      "Teacher of the Hearing Impaired",
      "Teacher of the Sight Impaired",
      "Technical Cable Jointer",
      "Technical Director",
      "Technical Sales Representative",
      "Technical Writer",
      "Technician (Agricultural)",
      "Technician (Architectural, Building & Surveying)",
      "Technician (Civil Engineering)",
      "Technician (Dental)",
      "Technician (Electrical Engineering)",
      "Technician (Electronic Engineering)",
      "Technician (Gallery, Library and Museum)",
      "Technician (ICT Support)",
      "Technician (Mechanical Engineering)",
      "Technician (Medical)",
      "Technician (Building and Engineering)",
      "Technician (Performing Arts)",
      "Technician (Science)",
      "Technician and Trades Worker",
      "Telecommunications Cable Jointer",
      "Telecommunications Engineering Professional",
      "Telecommunications Engineer",
      "Telecommunications Field Engineer",
      "Telecommunications Linesworker",
      "Telecommunications Network Engineer",
      "Telecommunications Network Planner",
      "Telecommunications Technical Officer and Technologist",
      "Telecommunications Technical Specialist",
      "Telecommunications Technician",
      "Telecommunications Trades Worker",
      "Telemarketer",
      "Telephone Betting Clerk",
      "Telephone Operator",
      "Television Equipment Operator",
      "Television Journalist",
      "Television Presenter",
      "Tennis Coach",
      "Test Analyst (ICT)",
      "Textile & Footwear Production Machine Operator",
      "Textile Dyeing and Finishing Machine Operator",
      "Textile, Clothing and Footwear Mechanic",
      "Therapy Aide",
      "Thoracic Medicine Specialist",
      "Ticket Collectors and Usher",
      "Ticket Salesperson",
      "Ticket Seller",
      "Tiler (Floor)",
      "Tiler (Roof)",
      "Tiler's Assistant",
      "Timber and Wood Process Worker",
      "Toolmaker",
      "Toolmaker and Engineering Patternmaker",
      "Tour Guide",
      "Tourism and Travel Adviser",
      "Tourist Information Officer",
      "Tow Truck Driver",
      "Train and Tram Driver",
      "Train Controller",
      "Train Driver",
      "Train Examiner",
      "Trainer (Animal)",
      "Trainer (ICT)",
      "Training and Development Professional",
      "Tram Driver",
      "Translator",
      "Transport and Despatch Clerk",
      "Transport Company Manager",
      "Transport Conductor",
      "Transport Engineer",
      "Transport Operations Inspector",
      "Transport Services Manager",
      "Travel Agency Manager",
      "Travel Agent",
      "Travel Attendant",
      "Travel Consultant",
      "Tree Faller",
      "Tree Surgeon",
      "Trekking Guide",
      "Tribunal Member",
      "Trimmer (Vehicle)",
      "Trolley Collector",
      "Truck Driver",
      "Truck Driver's Offsider",
      "Trust Officer",
      "Turf Grower",
      "Tutor and Lecturer (University)",
      "Tutor and Teacher (Private)",
      "Typist",
      "Tyre Fitter",
      
      "Undertaker",
      "University Lecturer",
      "University Lecturers and Tutor",
      "University Tutor",
      "Upholsterer",
      "Urban and Regional Planner",
      "Urologist",
      "Usher",
      
      "Valuer",
      "Vascular Surgeon",
      "Vegetable Farm Worker",
      "Vegetable Grower",
      "Vegetable Picker",
      "Vehicle and Vehicle Parts Salesperson",
      "Vehicle Assembler",
      "Vehicle Body Builder",
      "Vehicle Body Builder and Trimmer",
      "Vehicle Painter",
      "Vehicle Parts and Accessories Fitter",
      "Vehicle Trimmer",
      "Vending Machine Attendant",
      "Veterinarian",
      "Veterinary Nurse",
      "Video Editor",
      "Video Producer",
      "Vineyard Worker",
      "Visual Arts and Crafts Professional",
      "Visual Merchandiser",
      "Vocalist",
      "Vocational Education Teacher",
      
      "Waiter",
      "Waitress",
      "Wall and Floor Tiler",
      "Ward Clerk",
      "Wardsperson",
      "Warehouse Administrator",
      "Warehouse Assistant",
      "Waste Water and Water Plant Operator",
      "Watch and Clock Maker and Repairer",
      "Water Inspector",
      "Waterside Worker",
      "Weaving Machine Operator",
      "Web Administrator",
      "Web Designer",
      "Web Developer",
      "Web Master",
      "Weighbridge Operator",
      "Weight Loss Consultant",
      "Welder (First Class)",
      "Welfare Centre Manager",
      "Welfare Support Worker",
      "Welfare Worker",
      "Welfare, Recreation and Community Arts Worker",
      "Whitewater Rafting Guide",
      "Wholesaler",
      "Window Cleaner",
      "Window Dresser",
      "Wine Maker",
      "Winery Cellar Hand",
      "Wood and Wood Products Factory Worker",
      "Wood Machinist",
      "Wood Machinist and Other Wood Trades Worker",
      "Wood Processing Machine Operator",
      "Wood Turner",
      "Wool Buyer",
      "Wool Classer",
      "Wool Handler",
      "Word Processing Operator",
      "Workplace Relations Adviser",
      "Writer (Author)",
      "Writer (Journalist and Other)",
      
      "Yarn Carding and Spinning Machine Operator",
      "Youth Worker",
      
      "Zookeeper",
      "Zoologist"
    ],
    designJSONS = {
      "misc":       [
        "man",
        "woman",
        "boy",
        "girl",
        "child",
        "monkey",
        "elephant",
        "deer",
        "horse",
        "cow",
        "sloth",
        "fox",
        "flying fox",
        "rhinoceros",
        "raccoon",
        "giraffe",
        "goat",
        "bat",
        "vampire bat",
        "megabat",
        "coyote",
        "otter",
        "sheep",
        "ghost",
        "alien",
        "mage",
        "caveman",
        "cavewoman",
        "elf",
        "fairy",
        "cyclops",
        "t-rex",
        "super hero",
        "super villain",
        "living statue",
        "gremlin",
        "parent",
        "centaur",
        "hobo",
        "skunk",
        "witch",
        "golem",
        "buddhist",
        "god",
        "fighter",
        "monster"
      ],
      "dogs":       [
        "dog",
        "labrador retriever",
        "pug",
        "siberian husky",
        "bulldog",
        "beagle",
        "pomeranian",
        "poodle",
        "chihuahua",
        "chow chow",
        "american pit bull terrier",
        "maltese",
        "boxer",
        "rottweiler",
        "golden tetriever",
        "dobermann",
        "shih tzu",
        "german shepherd",
        "yorkshire terrier",
        "great dane",
        "shiba ino",
        "dachshund",
        "french bulldog",
        "english mastiff",
        "samoyed dog",
        "shar pei",
        "pembroke welsh corgi",
        "greyhound",
        "st. bernard",
        "newfoundland dog",
        "jack russell terrier",
        "cavalier king charles spaniel",
        "american staffordshire terrier",
        "english cocker spaniel",
        "weimaraner",
        "american bully",
        "pekingese",
        "papillion",
        "bichon frise",
        "border collie",
        "west highland white terrier",
        "whippet",
        "austrialian shepherd",
        "sarabi mastiff",
        "pointer",
        "mexican hairless dog",
        "australian kelpie",
        "boston terrier",
        "cane corse",
        "akita",
        "bull terrier",
        "miniature pinscher"
      ],
      "felidae":    [
        "cat",
        "lion",
        "tiger",
        "leopard",
        "cheetah",
        "jaguar",
        "cougar",
        "wildcat",
        "lynx",
        "panther",
        "ocelot",
        "snow leopard",
        "caracal",
        "serval",
        "margay",
        "tigon",
        "jaguarundi",
        "leopard cat",
        "saber-toothed tiger",
        "clouded leopard",
        "palla",
        "oncilla",
        "jungle cat",
        "sand cat",
        "fishing cat",
        "rusty-spotted cat",
        "black-footed cat",
        "kodkod",
        "machairodontinae",
        "bay cat",
        "homotherium",
        "african golden cat",
        "asian golden cat",
        "pumapard",
        "puma",
        "machairodus",
        "andean mountain cat",
        "marbled cat",
        "flat-headed cat",
        "iriomote cat",
        "cat-fox",
        "siamese cat",
        "sphynx cat"
      ],
      "wolfs":      [
        "wolf",
        "arctic wolf",
        "northwestern wolf",
        "dingo",
        "japanese wolf",
        "eurasian wolf",
        "mexican wolf",
        "eastern wolf",
        "indian wolf",
        "italian wolf",
        "british columbia wolf",
        "hokkaido wolf",
        "great plains wolf",
        "tundra wolf",
        "interior Alaskan wolf",
        "arabian wolf",
        "alaskan tundra wolf"
      ],
      "bears":      [
        "bear",
        "polar bear",
        "brown bear",
        "american black bear",
        "asian black bear",
        "giant panda",
        "sloth bear",
        "spectacled bear",
        "kodiak bear",
        "eurasian brown bear",
        "tremarctos",
        "himalayan brown bear",
        "kamchatka brown bear",
        "kermode bear",
        "louisiana black bear",
        "alaska peninsula brown bear",
        "florida black bear",
        "california grizzly bear",
        "syrian brown bear",
        "glacier bear",
        "cinnamon bear",
        "ussuri brown bear",
        "tibetan blue bear",
        "pizzly",
        "formosan black bear",
        "siri lankan sloth bear",
        "mexican black bear",
        "balochistan black bear",
        "california black bear",
        "newfoundland black bear",
        "olympic black bear",
        "gobi bear",
        "new mexico black bear"
      ],
      "rodents":    [
        "rabbit",
        "squirrel",
        "mouse",
        "rat",
        "hampster",
        "beaver",
        "chinchilla",
        "gerbil",
        "coypu",
        "golpher",
        "agouti",
        "lemming",
        "dormouse",
        "cavies",
        "guinea pig",
        "degu",
        "blesmol",
        "paca",
        "hystricomorpha",
        "porcupine",
        "pedetes",
        "flying mouse",
        "flying squirrel"
      ],
      "birds":      [
        "hawk",
        "red-tailed hawk",
        "cooper's hawk",
        "eagle",
        "bald eagle",
        "golden eagle",
        "white-tailed eagle",
        "harpy eagle",
        "crowned eagle",
        "black eagle",
        "white-bellied sea eagle",
        "tawny eagle",
        "seagull",
        "pelican",
        "tern",
        "black-winged kite",
        "mississippi kite",
        "vulture",
        "turkey vulture",
        "griffon vulture",
        "bearded vulture",
        "new world vulture",
        "egyptian vulture",
        "lappet-faced vulture",
        "white-rumped vulture",
        "king vulture",
        "cape vulture",
        "kite",
        "falcon",
        "pigeon",
        "dove",
        "owl",
        "hummingbird",
        "penguin",
        "swallow",
        "finches",
        "sparrow",
        "toucan",
        "heron",
        "thrush",
        "bird-of-pradise",
        "woodpecker",
        "albatross",
        "ibis",
        "wren",
        "passerine",
        "crane",
        "stork",
        "bulbul",
        "swifts",
        "hornbill",
        "moa",
        "hoopoes",
        "cormorant",
        "potoo",
        "polver",
        "cuckoo",
        "sternidae",
        "lark",
        "goose",
        "grouse",
        "accipitriform (hawks, eagles, and kites)",
        "fowl",
        "flamingo",
        "guineafowl",
        "bustard",
        "terror bird",
        "kingfisher",
        "turaco",
        "sandpiper",
        "shorebird",
        "laridae",
        "waterfowl",
        "grebes",
        "auk",
        "gull",
        "bee-eater",
        "rail",
        "turkey",
        "chicken",
        "rooster"
      ],
      "parrots":    [
        "parrot",
        "cockatoo",
        "lovebird",
        "macaw",
        "new zealand parrot (Strigopidae)"
      ],
      "insects":    [
        "beetle",
        "bee",
        "wasp",
        "ant",
        "mosquito",
        "butterfly",
        "moth",
        "fly",
        "cricket",
        "horse-fly",
        "flea",
        "ladybird beetle (aka ladybug)",
        "termite",
        "cicadoidea",
        "dragonfly",
        "mantis",
        "earwig",
        "firefly (aka lightning bug)",
        "grasshopper",
        "botfly",
        "lice",
        "booklice"
      ],
      "arthropods": [
        "spider",
        "crustaocean",
        "scorpion",
        "crab",
        "tick",
        "centipede",
        "millipede",
        "shrimp"
      ],
      "reptiles":   [
        "turtle",
        "lizard",
        "dinosaur",
        "flying dinosaur",
        "chameleon",
        "crocodile",
        "gecko",
        "skink",
        "iguana",
        "lacertid",
        "gekkota",
        "hylonomus"
      ],
      "amphibians": [
        "frog",
        "toad",
        "salamander",
        "caecilian"
      ],
      "snakes":     [
        "anaconda",
        "viper",
        "python",
        "mamba",
        "cobra",
        "kingsnake",
        "colubrid snake",
        "taipan",
        "garter snake",
        "boa",
        "elapid snake",
        "coral reef snake",
        "anilius"
      ],
      "fish":       [
        "fish",
        "shark",
        "whale",
        "trout",
        "salmon",
        "cod",
        "bass",
        "perch",
        "hake",
        "sardine",
        "sole",
        "plaice",
        "minnow",
        "billfish",
        "platy",
        "tetra",
        "pufferfish",
        "catfish",
        "flathead catfish",
        "cory catfish",
        "bristlenose catfish",
        "snakehead",
        "bowfin",
        "herring",
        "halibut",
        "tilapia",
        "common carp",
        "goldfish",
        "siamese fighting fish",
        "guppy",
        "northern pike",
        "wels catfish",
        "gilt-head bream",
        "european bass",
        "zander",
        "baramundi",
        "mahi-mahi",
        "blue tang",
        "japanese amberjack",
        "european perch",
        "muskellunge",
        "atlantic cod",
        "atlantic mackerel",
        "arapaima gigas",
        "oscar",
        "common ling",
        "european eel",
        "angler",
        "lophius piscatorius",
        "turbot",
        "tench",
        "squalius cephalus",
        "burbot",
        "iridescent shark",
        "garfish",
        "common molly",
        "common break",
        "common roach",
        "rainbow trout",
        "flathead grey mullet",
        "neon tetra",
        "green swordtail",
        "ocean sunfish",
        "pollock",
        "arctic char",
        "haddock",
        "great white shark",
        "merluccius merluccius (aka cornish salmon)",
        "candiru",
        "atlantic salmon",
        "atlantic horse mackerel",
        "common dentex",
        "southern platyfish",
        "ide",
        "bluegill",
        "brown trout",
        "pollack",
        "largemouth bass",
        "smallmouth bass",
        "algae eater",
        "barbel",
        "mahseer",
        "kokopu",
        "gudgeon",
        "darter",
        "tigerfish",
        "silver dollar",
        "barb",
        "upside-down catfish",
        "pacu",
        "cisco",
        "longperch",
        "seer",
        "headstander",
        "red seabream",
        "green spotted puffer",

        "hammerhead",
        "catshark",
        "sand shark",
        "sawshark",
        "angel shark",
        "angular roughshark",
        "carpet shark",
        "orca (aka killer whale)",
        "blue whale",
        "sperm whale",
        "humpback whale",
        "beluga whale",
        "narwhal",
        "gray whale",
        "fin whale",
        "bowhead whale",
        "north atlantic right whale",
        "north pacific right whale",
        "livyatan",
        "dolphin",
        "amazon river dolphin",
        "short-finned pilot whale",
        "bryde's whale",
        "sothern right whale",
        "sei whale",
        "false killer whale",
        "baiji",
        "common minke whale",
        "long-finned pilot whale",
        "south asian river dolphin",
        "pygmy sperm whale",
        "omura's whale",
        "northern bottlenose whale",
        "dward sperm whale",
        "la plata dolphin",
        "pygmy right whale",
        "southern bottlenose whale",
        "strap-toothed whale",
        "sowerby's beaked whale",
        "antarctic minke whale",
        "tropical bottlenose whale",
        "ginkgo-toothed beaked whale",
        "pygmy beaked whale",
        "andrew's beaked whale",
        "gray's beaked whale",
        "shepherd's beaked whale",
        "hector's beaked whale"
      ]
    },
    JSONItems   = [
      "standard",
      "dogs",
      "felidae",
      "wolfs",
      "bears",
      "rodents",
      "birds",
      "parrots",
      "insects",
      "arthropods",
      "reptiles",
      "amphibians",
      "snakes",
      "fish"
    ];

// generate a random number
function randomNumber(n) {
  return Math.floor( Math.random() * n );
}

// add/remove animateCSS animations
function testAnim(el, x) {
  $("#" + el).removeClass().addClass(x).one("webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend", function(){
    $(this).removeClass();
  });
};

function init() {
  ranMood     = randomNumber(moodsJSON.length);
  ranMood     = moodsJSON[ranMood];
  moodLink    = " <a class=\"whitetxt\" href=\"https://duckduckgo.com/?q="+ ranMood.replace(/ /, '+') +"+characteristic&t=h_&ia=web\" target=\"_blank\"><i class=\"fa fa-external-link\"></i></a>";
  ranJob      = randomNumber(jobsJSON.length);
  ranJob      = jobsJSON[ranJob];
  jobLink     = " <a class=\"whitetxt\" href=\"https://duckduckgo.com/?q=what+is+a+"+ ranJob.toLowerCase().replace(/ /, '+') +"%3F&t=h_&ia=web\" target=\"_blank\"><i class=\"fa fa-external-link\"></i></a>";
  ranJSONItem = JSONItems[randomNumber(JSONItems.length)];
  grabJSObj   = designJSONS[""+ ranJSONItem +""];
  output      = grabJSObj[ randomNumber(grabJSObj.length) ];
  
  // with duckduckgo images search link
  output      = output + " <a class=\"whitetxt\" href=\"https://duckduckgo.com/?q="+ output.replace(/ /, '+') +"+"+ ranJSONItem +"&t=h_&iax=images&ia=images\" target=\"_blank\"><i class=\"fa fa-external-link\"></i></a>";
  
  // detect if mood starts with a vowel or not
  str = ranMood.substring(0, 1).toLowerCase();
  if (str === "a" || str === "e" || str === "i" || str === "o" || str === "u") {
    ranMood = "an " + ranMood;
  } else {
    ranMood = "a " + ranMood;
  }
  
  // detect if job starts with a vowel or not
  str = ranJob.substring(0, 1).toLowerCase();
  if (str === "a" || str === "e" || str === "i" || str === "o" || str === "u") {
    ranJob = "an " + ranJob;
  } else {
    ranJob = "a " + ranJob;
  }
  
  // generate character to draw
  character.innerHTML = ranMood + moodLink + " " + output;
  scenario.innerHTML = "Category: " + ranJSONItem + "<br>Draw: " + ranMood + moodLink + " " + output + "<br>Who is " + ranJob + jobLink + "<br>&nbsp;";
  return false;
}

// initiate animation and character generation
testAnim("character", "animated rubberBand delay-2s");
testAnim("scenario", "animated pulse delay-2s");
init();

// generate character and reset animation upon button click
generate.onclick = function() {
  testAnim("character", "animated rubberBand delay-2s");
  testAnim("scenario", "animated bounce delay-2s");
  init();
};
